### ISSUE TITLE
ACME plugin: custom ACME server URL

### ISSUE THREAD

**Issue by Gauss23** [opnsense/plugins#2547] opened 2021-09-24 14:49 UTC
Hi,

as the title says: the ACME plugin is currently limited to 6 hard coded ACME server URLs.
It should be possible to add a custom ACME server URL, to use an internal ACME server (i.e. step-ca) for certificate distribution.

Best regards.

**Comment by fraenki** [comment] 2021-10-10 21:01
duplicate of #2173 and #1569

**Closed by fraenki** 2021-10-10 21:01 UTC
Labels: incomplete
