### ISSUE TITLE
[Dynamic DNS (dd-client)] `Invalid Value for keyword 'ipv6' = 'yes'`

### ISSUE THREAD

**Issue by giggio** [opnsense/plugins#3307] opened 2023-02-14 01:07 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
I'm getting this log:

```
[meta sequenceId="1"] WARNING: file /usr/local/etc/ddclient.conf, line 3: Invalid Value for keyword 'ipv6' = 'yes'
```

**To Reproduce**
1. Create a Dynamic DNS configuration;
2. See error logs.

**Expected behavior**
No error logs

**Screenshots**
N/A

**Relevant log files**
N/A

**Additional context**
This is the `/usr/local/etc/ddclient.conf` file:

```ini
syslog=yes                  # log update msgs to syslog
pid=/var/run/ddclient.pid   # record PID in file.
ipv6=yes
ssl=yes


use=cmd, cmd="/usr/local/opnsense/scripts/ddclient/checkip -i pppoe0 -t 1 -s googledomains --timeout 10",
protocol=noip, \
login=<redacted>, \
password=<redacted> \
<redacted>.no-ip.info
```

**Environment**
Software version used and hardware type if relevant.

OPNsense 23.1_6-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s 1 Nov 2022

**Comment by AdSchellevis** [comment] 2023-02-14 07:45
looking at their code (https://github.com/ddclient/ddclient/blob/v3.10.0_2/ddclient.in) the `ipv6=yes` has been replaced by something else. You should probably duplicate the `use` with `usev6` and `checkip` script likely needs work as well to ask for a v6 address in that case with an additional paramater. marking this ticket help-wanted to see if anyone wants to contribute with the pointers provided.

**Comment by Arvoreen75** [comment] 2023-02-18 23:04
Hello, I am no expert with OPNSense coding, but I needed a quick fix to get ipv6 working so this is what I did.
i edited this file: /usr/local/opnsense/service/templates/OPNsense/ddclient/ddclient.conf

and here the diff:
6a7,9
> {% if not helpers.empty('OPNsense.DynDNS.general.allowipv6') %}
> ipv6=yes
> {% endif %}
26,28d28
< {%          if not helpers.empty('OPNsense.DynDNS.general.allowipv6') %}
< use=if, usev6=ifv6, if={{physical_interface(account.interface)}}, \
< {%          else %}
30d29
< {%          endif %}

**Comment by mjenny** [comment] 2023-03-19 12:31
Apparently `use=if` is deprecated. However, replacing `use=if, if=igb1` with `usev4=ifv4, ifv4=igb1` doesn't seem to be working (replaced actual hostname with [HOSTNAME]):
```
root@OPNsense:/usr/local/etc # ddclient update --force
WARNING:  '' is not a valid IPv4 or IPv6 address
WARNING:  found neither IPv4 nor IPv6 address
WARNING:  [HOSTNAME]: unable to determine IP address with strategy use=ip
Use of uninitialized value $_[2] in sprintf at /usr/local/sbin/ddclient line 2163.
SUCCESS:  updating [HOSTNAME]: good: IP address set to 
```

This is the config used:
```
syslog=yes                  # log update msgs to syslog
pid=/var/run/ddclient.pid   # record PID in file.
ssl=yes


usev4=ifv4, ifv4=igb1, \
protocol=dyndns2, \
server=[SERVER], \
login=[LOGIN], \
password=[PASSWORD] \
[HOSTNAME]
```

This should actually be working according to the ddclient help:
```
[...]
-use <which>          : deprecated, see 'usev4' and 'usev6' (default: ip).
    -use=ip                     : deprecated, see 'usev4' and 'usev6'.
    -use=web                    : deprecated, see 'usev4' and 'usev6'.
    -use=if                     : deprecated, see 'usev4' and 'usev6'.
[...]
-usev4 <which>             : how the should IPv4 address be obtained. (default: disabled).
[...]
    -usev4=ifv4                   : obtain IPv4 from the -ifv4 {interface}.
[...]
Options that apply to 'use=if':
  -if <interface>       : deprecated, use 'ifv4' or 'ifv6' (default: ppp0).
  -ifv4 <interface>     : obtain IPv4 address from <interface> (default: default).
  -ifv6 <interface>     : obtain IPv6 address from <interface> (default: default).
[...]
```

**Comment by bskinner** [comment] 2023-04-08 04:56
I just sunk a couple hours into trying to figure this one out, so hopefully this helps some folks.

Confirming what a few other folks have echoed here- `ipv6=yes` is no longer supported in the [3.10.0](https://github.com/ddclient/ddclient/releases/tag/v3.10.0) release, and has been replaced by `usev4`/`usev6`. One additional gotcha here is that `use` should also be set to `no` (the docs say `disabled` is also allowed, but it doesn't seem to be properly parsed at the moment). If you don't clear out the `use` option, its default value of `ip` will be used, and you'll get messages like `unable to determine IP address with strategy use=ip` printed.

There is also a [known issue](https://github.com/ddclient/ddclient/issues/427) with the `usev6`/`usev4` options not being parsed per-host, and only when used globally. The issue is fixed in ddclient/ddclient#505, but that version has not been released yet. This is why the `usev4` and `usev6` options are in the `global` part in the below example config.

Below is config that works on my system, and successfully updates both the `A` and `AAAA`  records for a domain I have with Cloudflare
```
syslog=yes                         # log update msgs to syslog
pid=/var/run/ddclient.pid   # record PID in file.
verbose=yes
ssl=yes

###
## Use this form if you have separate IPv4 and IPv6 interfaces, and remove the `if=igb0` line  from the host definition below
# usev4=ifv4, ifv4=igb0  # Replace `igb0` with the IPv4 interface you want to use.
# usev6=ifv6, ifv6=igb0  # Replace `igb0` with the IPv6 interface you want to use

## If the desired IPv4 and IPv6 addresses you want are on the same interface, you can get by with just this.
##    The default interface will be specified by `if`.
usev4=ifv4
usev6=ifv6

use=no, \
if=igb0, \  # Replace with your target interface
protocol=cloudflare, \
zone=domain.example, \
password=CLOUDFLARE-API-TOKEN\
host.domain.example
```

In order to get things working, I ssh'd in to my opnsense box, overwrite the configuration located at `/usr/local/etc/ddclient.conf`, and restarted `ddclient` with `sudo service ddclient restart`. I don't know what triggers a rewrite of the configuration file, so I've just been avoiding the ddclient part of the gui entirely.

I was testing modifications to the ddclient configuration using
```
# While logged in as root
service ddclient stop

# You can add the `-force` flag below to force an update, even if one is not needed
ddclient -foreground -v -debug -verbose -noquiet-daemon=0 -file /usr/local/etc/ddclient.conf
```

And now I'm going to get some sleep- best of luck, y'all.

**Comment by fichtner** [comment] 2023-04-11 09:05
@bskinner thanks for the analysis... how about we pull https://github.com/ddclient/ddclient/commit/11a5bd5e and https://github.com/ddclient/ddclient/commit/5596ee83d16 and fix whatever needs to be fixed on our side in the configuration (if any)?

**Comment by bskinner** [comment] 2023-04-12 01:57
Tried out the test package and it looks good in my test case! An update was triggered for *both* the `A` and `AAAA` records for my domain in one go, with a single host entry in the `ddclient.conf` (tested using the direct invocation of `ddclient` used in my previous comment).

The config I used is below (minus the secrets):

```
syslog=yes                  # log update msgs to syslog
pid=/var/run/ddclient.pid   # record PID in file.
verbose=yes
ssl=yes

use=no, \
usev4=ifv4, usev6=ifv6 \
if=igb0 \
protocol=cloudflare, \
zone=domain.example, \
password=CLOUDFLARE_API_TOKEN \
sub.domain.example
```

**Comment by fichtner** [comment] 2023-04-13 06:45
@bskinner thanks a lot for your help. does this look reasonable to you? db794e2

I've left out the use=no because that is supposed to be taken care of by https://github.com/ddclient/ddclient/commit/5596ee83d16

To install:

    # opnsense-revert os-ddclient && opnsense-patch -c plugins db794e2

**Comment by fichtner** [comment] 2023-04-13 07:04
Also added a bit of validation for empty interface problem 0f0e8c353176f46

I guess some people don't set this up right and complain it's not working. ;)

**Comment by bskinner** [comment] 2023-04-14 03:05
Awesome. Looked things over and the changes seem reasonable. I overlooked the changes to the `use` behavior, so that's a nice find!

Testing-wise, I patched my instance and the generated configuration file looks correct for both the ipv6/ipv4 and ipv4-only cases (sanitized configs below), and the correct records were updated for both cases.

Thank you for putting together these fixes!

## Post-patch generated configurations
### IPv4-only
syslog=yes                  # log update msgs to syslog
pid=/var/run/ddclient.pid   # record PID in file.
verbose=yes

ssl=yes

usev4=ifv4, if=igb0, \
protocol=cloudflare, \
zone=domain.example, \
password=CLOUDFLARE_SECRET \
sub.domain.example
```

### IPv4 & IPv6
```
syslog=yes                  # log update msgs to syslog
pid=/var/run/ddclient.pid   # record PID in file.
verbose=yes

ssl=yes

usev6=ifv6, \
usev4=ifv4, if=igb0, \
protocol=cloudflare, \
zone=domain.example, \
password=CLOUDFLARE_SECRET \
sub.domain.example
```

**Comment by fichtner** [comment] 2023-04-14 06:14
@bskinner thanks a lot, these updates go to 23.1.6 next week then!

Cheers,
Franco

**Closed by fichtner** 2023-04-14 06:14 UTC
Labels: bug
