### ISSUE TITLE
NUT:Blazer_ser driver permission 

### ISSUE THREAD

**Issue by woooow1** [opnsense/plugins#964] opened 2018-11-09 09:21 UTC
After update plugin i have troubles with connection with ups. Now: permissions issue. 
nut_daemon and nut_upsmon not start. Here is log:

nut not running? (check /var/db/nut/upsd.pid).
Network UPS Tools - UPS driver controller 2.7.4
Network UPS Tools - Megatec/Q1 protocol serial driver 1.57 (2.7.4)

Unable to open /dev/ttyu1: Permission denied

  Current user id: uucp (66)
Serial port owner: root (0)
Serial port group: wheel (0)
     Mode of port: 0600

Things to try:

 - Use another port (with the right permissions)

 - Fix the port owner/group or permissions on this port

 - Run this driver as another user (upsdrvctl -u or 'user=...' in ups.conf).
   See upsdrvctl(8) and ups.conf(5).

Fatal error: unusable configuration
Driver failed to start (exit status=1)
/usr/local/etc/rc.d/nut: WARNING: failed precmd routine for nut
root@kiro:~ #  service nut restart
nut not running? (check /var/db/nut/upsd.pid).
Network UPS Tools - UPS driver controller 2.7.4
Network UPS Tools - Megatec/Q1 protocol serial driver 1.57 (2.7.4)

Unable to open /dev/ttyu1: Permission denied

  Current user id: uucp (66)
Serial port owner: root (0)
Serial port group: wheel (0)
     Mode of port: 0600

Things to try:

 - Use another port (with the right permissions)

 - Fix the port owner/group or permissions on this port

 - Run this driver as another user (upsdrvctl -u or 'user=...' in ups.conf).
   See upsdrvctl(8) and ups.conf(5).

Fatal error: unusable configuration
Driver failed to start (exit status=1)
/usr/local/etc/rc.d/nut: WARNING: failed precmd routine for nut

**Comment by woooow1** [comment] 2018-11-09 09:37
In 2 places i see set permissions for nut:

/usr/local/etc/devd/nut-usb.conf - action "chgrp uucp /dev/$cdev; chmod g+rw /dev/$cdev"; on every device

/usr/local/opnsense/scripts/OPNsense/Nut/setup.sh - chown uucp:uucp /var/db/nut

The main question for me is how to add nut services to use serial port, that is owned to root?

**Comment by woooow1** [comment] 2018-11-09 11:13
Finally get everything to work. Ups monitor not start, because in template is missing option to add required settings in config files if blazer_ser driver is enabled. In ups.conf template add option user=root before ups name.
I think, this way is better.
Here is moded templates: 

[ups.conf.txt](https://github.com/opnsense/plugins/files/2565603/ups.conf.txt)

[upsmon.conf.txt](https://github.com/opnsense/plugins/files/2565606/upsmon.conf.txt)

**Comment by mimugmail** [comment] 2018-11-09 11:17
Thanks for you analysis, do you want to commit on your own or shall I do it?

**Comment by woooow1** [comment] 2018-11-09 11:22
If you think, that this solution is good for commit, do it. For me it works!

**Comment by mimugmail** [comment] 2018-11-09 11:43
It looks like a one-liner .. I'll try it later today, must finish some other stuff first.
Thanks for digging into it 👍

**Comment by woooow1** [comment] 2018-11-09 12:02
I think, better way is to add option in gui for user=root! I dont know if it is nut general problem with real serial port.

**Comment by woooow1** [comment] 2018-11-10 13:44
# ls -l /dev/ttyu*
crw-------  1 root  wheel  0x2c Nov 10 15:37 /dev/ttyu0
crw-------  1 root  wheel  0x2d Nov 10 15:01 /dev/ttyu0.init
crw-------  1 root  wheel  0x2e Nov 10 15:01 /dev/ttyu0.lock
crw-------  1 root  wheel  0x32 Nov 10 15:37 /dev/ttyu1
crw-------  1 root  wheel  0x33 Nov 10 15:01 /dev/ttyu1.init
crw-------  1 root  wheel  0x34 Nov 10 15:01 /dev/ttyu1.lock

Here is my configuration. Maybe we must add user uucp to group wheel/dialout?

**Comment by fichtner** [comment] 2018-11-10 14:00
no, group uucp and group read-write seems enough IMO

**Comment by woooow1** [comment] 2018-11-10 15:10
ttyXX must be selectable. something like,in gui, with arguments???
Im open for test... I dont know if it is possible to add lines via defined arguments in setup.sh?

chown :uucp /dev/
chmod 660 /dev/ 

this is predefined and user only add port number...

**Comment by woooow1** [comment] 2018-11-12 15:01
@fichtner This 2 lines in setup.sh not work. Maybe i forgot to remove root from ups.conf :(
When add this commands in terminal, driver start to work.
Im stay with root solution for now! I dont have enough time to investigate!
If you decide, close ticket!

**Comment by mimugmail** [comment] 2018-11-12 19:13
@fichtner maybe a checkbox just for this driver in forms? Since we only add working confirmed drivers this should be OK.

**Comment by woooow1** [comment] 2018-11-13 12:13
Yesterday i add setup.sh in template. In forms only for blazerser add checkbox and arguments for select right port. Now if checkbox is enabled, in startup.sh is added chmod and chwon, suggested by @fichtner, but after reboot, system not apply commands. When i remove setup.sh from templating and add lines, driver start to work. Im confused. Where im wrong??? In gui looks like this: 
![1](https://user-images.githubusercontent.com/43699588/48412607-d9f4d780-e74d-11e8-8770-f18b92043007.jpg)

@mimugmail  here is files, take a look and tell me where im wrong.

**Comment by woooow1** [comment] 2018-11-13 12:20
@mimugmail yesterday add setup.sh in template. Now if checkbox is enabled, in script is write fix suggested by @fichtner. But after reboot, system not apply permissions. When i remove setup.sh from tempate and set lines again, fix is ok. Im confused...

[setup.sh.txt](https://github.com/opnsense/plugins/files/2576193/setup.sh.txt)
[settings.xml.txt](https://github.com/opnsense/plugins/files/2576194/settings.xml.txt)
[Nut.xml.txt](https://github.com/opnsense/plugins/files/2576195/Nut.xml.txt)

Take a look at tell me where im wrong.

**Comment by mimugmail** [comment] 2018-11-13 13:15
@woooow1 setup.sh is static and not templated, that's why here's no progress.
I'm still for adding user=root in the driver section ..

**Comment by mimugmail** [comment] 2018-11-14 07:54
@woooow1 
Just to be sure .. when you add static:

chown :uucp /dev/ttyu0
chmod 660 /dev/ttyu0
chown :uucp /dev/ttyu1
chmod 660 /dev/ttyu1

and reboot .. does it work?

**Comment by woooow1** [comment] 2018-11-14 09:02
Yes, chown :uucp /dev/ttyu1 and chmod 660 /dev/ttyu1 work in static setup.sh!
ttyu0 is use for another purpose!

**Comment by mimugmail** [comment] 2018-11-14 10:18
@fichtner 
Include in setup.sh a script which is templated? Then a checkbox which will template the chmod?

**Comment by fichtner** [comment] 2018-11-14 10:59
we can't template setup.sh for sanity reasons. question now is how is ttyuX selected? do we have this information or does nut do this on its own?

**Comment by fichtner** [comment] 2018-11-15 07:21
@woooow1 the devd.conf should work, the plugin can ship such rules which would make detection of devices easier and pluggable...

**Comment by woooow1** [comment] 2018-11-15 14:13
Its possible to make file, like nut-usb.conf, but for serial device?
When I run commands, that is in file from terminal, driver start to work.

**Comment by fichtner** [comment] 2018-11-15 14:13
the devd.conf file can be bundled with the plugin if that's what you mean, yes...

**Comment by woooow1** [comment] 2018-11-15 14:44
Ok, lets try. How to test?

**Comment by mimugmail** [comment] 2018-11-25 05:37
@fichtner can you give me a hint about how to integrate the files with plugin? Just via TARGETS?

**Comment by fichtner** [comment] 2018-12-03 20:57
@mimugmail like any other file... we have them in core too:

https://github.com/opnsense/core/tree/master/src/etc/devd

just drop in a nut.conf file...

**Comment by mimugmail** [comment] 2018-12-27 11:42
@woooow1 I'd need the vendor id and product id you'll see in the status to add such a file.

**Comment by woooow1** [comment] 2018-12-30 14:01
I dont have such info in status page!

battery.charge: 100
battery.voltage: 14.00
battery.voltage.high: 13.00
battery.voltage.low: 10.40
battery.voltage.nominal: 12.0
device.mfr:
device.model:
device.type: ups
driver.name: blazer_ser
driver.parameter.pollinterval: 2
driver.parameter.port: /dev/ttyu1
driver.parameter.synchronous: no
driver.version: 2.7.4
driver.version.internal: 1.57
input.current.nominal: 0.0
input.frequency: 50.0
input.frequency.nominal: 50
input.voltage: 227.0
input.voltage.fault: 140.0
input.voltage.nominal: 220
output.voltage: 226.5
ups.beeper.status: enabled
ups.delay.shutdown: 30
ups.delay.start: 180
ups.firmware: TR00071G
ups.load: 7
ups.mfr:
ups.model:
ups.status: OL
ups.temperature: 30.0
ups.type: offline / line interactive

**Comment by mimugmail** [comment] 2018-12-31 13:45
@fichtner no idea how to manage this with devd files when there's no vendor or product id, as with nut-usb.conf from devd it's only matching against these two.

**Comment by woooow1** [comment] 2019-01-02 09:39
@mimugmail @fichtner I make research in other distribution, how nut blazer_ser is running and seems to me, that driver run also with root access.
Here is part of start script:

rc_start() {
	echo starting NUT
	/usr/bin/killall -q -9 upsmon
	/usr/bin/killall -q -9 upsd
	/usr/bin/killall -q -9 upsdrvctl
	/usr/bin/killall -q -9 blazer_ser
	/usr/local/sbin/upsmon
	/usr/local/sbin/upsdrvctl start &
	sleep 1
	/usr/local/sbin/upsd -u root
	return 0

**Comment by mimugmail** [comment] 2019-10-12 15:51
@fichtner to close this one I'd suggest to add `user=root` for this driver and add a warning.

**Comment by fichtner** [comment] 2019-10-12 16:26
I am unsure what the issue is with setting up the user to be able to operate all the things it needs :/

**Comment by mimugmail** [comment] 2019-10-12 17:09
The process needs to run with proper permissions to access the tty. As only the upsmon process will switch its permissions I'm ok with it. Otherwise we better close.

**Comment by fichtner** [comment] 2019-11-11 07:04
@mimugmail after much thought let's just do root for this driver and be done with it. please add a warning 👍

**Closed** 2019-11-11 17:24 UTC
Labels: bug
