### ISSUE TITLE
DynDNS provider Route53 v6 not working

### ISSUE THREAD

**Issue by theq86** [opnsense/plugins#509] opened 2018-01-22 19:30 UTC
When trying to update the IPv6 address on Amazon Route53 I always get the following error:

opnsense: /services_dyndns_edit.php: Route53::listResourceRecordSets(): Sender - AccessDenied: User: arn:aws:iam::575452484744:user/dyndns is not authorized to perform: GetHostedZone on resource: arn:aws:route53:::hostedzone/rrset Request Id: 11250012-ffaa-11e7-9c69-1deaea571495

This is somehow impossible, since the user has the policies: AmazonRoute53DomainsFullAccess, AmazonRoute53AutoNamingFullAccess, AmazonRoute53FullAccess.

edit: PLUS, you cannot set a Hosted Zone ID in the config for Route53 v6. This option is missing in the GUI. Without it, how does it know which Hosted Zone to update? In the v4 settings this option is available. Maybe this has to be added to v6 as well to make it work.

On IPv4 it works well. I'm using the same account and aws credentials for both IPv4 and IPv6.

If you need some more log or debugging data let me know

**Comment by theq86** [comment] 2018-01-22 19:33
closed because of wrong project. should go into opnsense/core

**Comment by fabianfrz** [comment] 2018-01-22 20:01
It should probably be here as os-dyndns is a plugin (dns/dyndns).

**Comment by theq86** [comment] 2018-01-22 20:07
thx, It was the right project after all...

I updated the first post with a possible cause. You can not set a hosted zone id in the Route53 v6 options.

**Comment by fichtner** [comment] 2018-01-22 21:30
ipv6 was added here: https://github.com/opnsense/plugins/pull/381

question is if this can be fixed or we need to update the library?

**Comment by theq86** [comment] 2018-01-22 21:58
I digged into this issue a bit. At first, a bug in the OPNsense GUI causes that the route53 options are not shown. This can be fixed easily.

When I fixed that still errors occured. But I think it's in the library code itself. Somehow the IPv6 address is used for some parameters where actually the IPv6 address should be used.

If I can fix it I will tell you.

**Comment by theq86** [comment] 2018-01-22 22:08
It seems the library developers did not think of people who use Route53 AND Route53 v6 with the SAME hostname configured.

I'm using home.mydomain.com in both v4 and v6. The lib works well, if I use different hostnames for different IP versions.

**Comment by theq86** [comment] 2018-01-22 22:12
PR https://github.com/opnsense/plugins/pull/510 fixes issue 1 which is part of the OPNsense GUI.
But I don't know how to proceed with the library itself.
The files needed to be fixed are:

plugins.inc.d/dyndns/phpDynDNS.inc
and plugins.inc.d/dyndns/r53.inc

Are those directly part of OPNsense or should their be fixed elsewhere?

**Comment by fichtner** [comment] 2018-01-23 06:49
Most of this seems to be dumped here.. https://github.com/aws/aws-sdk-php/tree/master/src

**Comment by theq86** [comment] 2018-01-23 07:48
The AWS SDK itself is not the problem. Can you tell me where I can get the dyndns library you use? If there is a newer version I would do the testing against the new version. If the bug still exists the best way would be to fix it in the library, get it fixed there and update it opnSense. I guess it would be possible to fix it in opnSense only but this should be our last resort if the library devs do not respond.

**Comment by fichtner** [comment] 2018-01-23 08:02
Dnydns library is free to update, it does no longer exist upstream. But now I’m confused, that means route 53 is not a problem and what you are describing has always been so?

**Comment by theq86** [comment] 2018-01-23 08:53
Yes, The SDK from Amazon is not the buggy thing here. It is the implementation of the library which calls the AWS SDK functions.

In short: In order to update the ResourceRecord on AWS, the dyndns library first retrieves the RR, then deletes it, then creates it new with the new IP address. The library retrieves the RRs by hostname, not by hostname and type (A or AAAA) and then takes the hardcoded array index 0 to get the specific RR.

If you have something like this, it works:

home.mydomain.com  A  127.0.0.1
home6.mydomain.com AAAA  ::1

because when RR for home6.mydomain.com is retrieved, the corresponding array has the correct RR only.

If you have something like me:

home.mydomain.com  A  127.0.0.1
home.mydomain.com AAAA  ::1

The 0 index forces the RR for IPv4 to be retrieved.

Then AWS of course says: No, I cannot delete the RR containing type AAAA and value 127.0.0.1
And No, I can not create a new AAAA record containing an IPv4 address.

The library must be more flexible. If there is no upstream any more we can just fix it in OPNsense.

**Comment by theq86** [comment] 2018-01-23 17:22
OK, PR https://github.com/opnsense/plugins/pull/515 will also fix the second bug.

We now don't rely on the assumption, that the correct RR is on index 0 inside the array. Rather we iterate through all found resource records and choose the appropriate RR for the type we want to update (A or AAAA).

**Comment by fichtner** [comment] 2018-01-23 17:26
Very nice, thank you!

**Comment by theq86** [comment] 2018-01-23 18:51
I re-added the PR for a cleaner history.

**Comment by fichtner** [comment] 2018-01-23 19:11
Should we include this in 18.1.1? I can't test so you need to vouch for it. Feel free to test this for a few days before answering. I'm ok with what you propose. :)

Closing the bug as the issue is addressed. Can always reopen if we need more work or continue in another ticket.

**Closed by fichtner** 2018-01-23 19:11 UTC
Labels: bug

**Comment by theq86** [comment] 2018-01-23 19:17
I patched my OPNSense live instance. When I forcefully update the dns entries it works.
I will observe the changes over the next 1-2 days if it all behaves correctly. e.g wether the automatic updates also work and so on. I will report here.

If it does I see no problem including it in 18.1.1 since these changes should not break anything ;-)

**Comment by theq86** [comment] 2018-01-24 09:20
There is still a cosmetic issue. Both, the dyndns widget and the dyndns overview show the dynamic ip address in two possible colors: 

greed - current IP is in sync with OPNSense cached file
red - otherwise

I tracked down the problem to the function _get_dyndns_ip_ ; file: _src/etc/inc/services.inc_ in the OPNSense core project.

The widget and the overview page call the above function to retrieve the current public ip on the interface. However, somehow on IPv6 this function returns the link-local address (fe80::<interface identifier>) and not the global unique address of the interface.

This leads to the ip address always shown red, because the cached file contains the correct external IP address.

Should we file a new bug in the core project? I think this is also easier to test for you since you do not need a dyndns provider.

**Comment by fichtner** [comment] 2018-01-24 09:21
Yes, ticket in core please :)

**Comment by theq86** [comment] 2018-01-24 09:33
For reference: Issue in opnsense/core
https://github.com/opnsense/core/issues/2128

**Comment by theq86** [comment] 2018-01-27 08:55
The fix is working. I tested it the last 3-4 days and it was reliable.
This fix should be released independently of https://github.com/opnsense/core/issues/2128 since they address different things.

**Comment by fichtner** [comment] 2018-01-27 10:28
Many thanks, merged as 4d9e9fed22f1f093 for 18.1.1 👍
