### ISSUE TITLE
[dynamic-dns]: Requires TTL value but box not shown

### ISSUE THREAD

**Issue by MrWowsers** [opnsense/plugins#1909] opened 2020-07-03 19:07 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
When trying to create a new Dynamic DNS for Namecheap I am told that 'Following input errors were detected': 'The TTL value needs to be a valid integer number.' However, the field does not appear. I do not think that it is required since my Namecheap account shows that it accepts Automatic (as well as 1, 5, 20, 30, 60 minutes). 

**To Reproduce**
1. Go to 'Services > Dynamic DNS'
2. Click on '+ Add'
3. Fill in the form.
    A. Choose Service type: Namecheap
    B. Interface: WAN
    C. Hostname
    D. Password
4. Click Save

**Expected behavior**
The entry should be saved OR a TTL box should be displayed to enter a value.

**Screenshots**
![image](https://user-images.githubusercontent.com/46585016/86492934-9ba29680-bd3d-11ea-84d2-a2c4142c70ff.png)

**Additional context**
I was able to workaround the problem by removing the display:none from the html.
New to Opnsense and this was the first time I was setting this up so I do not know when it was introduced.
This affects more than just Namecheap.

**Environment**
OPNsense 20.1.8-amd64 on Fitlet2
Intel(R) Celeron(R) CPU J3455 @ 1.50GHz (4 cores)
Intel i211

**Comment by fichtner** [comment] 2020-07-03 19:42
Duplicate of #1903 -- pushing a fix to 20.1.8 shortly, but since 20.1.8 was wrapped up before this was included we have to sit the situation out a bit.

**Closed by fichtner** 2020-07-03 19:42 UTC
