### ISSUE TITLE
NUT Config

### ISSUE THREAD

**Issue by awptechnologies** [opnsense/plugins#3259] opened 2023-01-13 05:53 UTC
I run a pretty big operation and I love opnsense. My only issue is nut. We need more configuration variables. Biggest one being forced shut down. Right now when an outage happens the box shuts down but it does it before everything else. Also because it doesn't send the forced shut down to ups it never fully enters an off state meaning power is not restored to servers when line power returns.

**Comment by awptechnologies** [comment] 2023-01-13 05:55
Would love to run opnsense as master but until the features in the configuration files are accessible, meaning they stay after update and reboot. This plug just isn't ready for the data center...

**Comment by fichtner** [comment] 2023-01-13 06:09
> Would love to run opnsense as master but until the features in the configuration files are accessible, meaning they stay after update and reboot. This plug just isn't ready for the data center...

Sure but how can it be if the data center guy just asks it to be ready? 😉

**Comment by Starkstromkonsument** [comment] 2023-01-28 22:36
duplicate of #2851

**Closed** 2023-01-29 10:04 UTC
Labels: incomplete
