### ISSUE TITLE
acme-client with DNS-01 doesn't validate domains/certificates

### ISSUE THREAD

**Issue by lrosenman** [opnsense/plugins#1366] opened 2019-06-13 14:36 UTC
The certificates renew fine, but the GUI doesn't know it.

<img width="1836" alt="Screen Shot 2019-06-13 at 9 35 40 AM" src="https://user-images.githubusercontent.com/2868525/59441708-a1d67580-8dbe-11e9-8bd6-0f75af8419b8.png">

What detail(s) do you need to diagnose this?

**Comment by StopTrain** [comment] 2019-06-15 03:49
Well, what method are you using to validate the DNS-01 challenge?

What do the logs say?

I just did a test run of my certificates and they all worked just fine and updated the acme status just fine and the issue/renewal date.

**Comment by lrosenman** [comment] 2019-06-15 15:33
nsupdate to my own DNS Server.
log: https://www.lerctr.org/~ler/dns_01.txt

**Comment by fraenki** [comment] 2019-06-19 12:07
Duplicate of #1307.

**Closed by fraenki** 2019-06-19 12:07 UTC
