### ISSUE TITLE
DNS Service DNS01 update the hostlist with ionos

### ISSUE THREAD

**Issue by HeinzKrischeu** [opnsense/plugins#2447] opened 2021-06-29 07:10 UTC
**Description**
I want to use opnsense for getting wild card certificates with my provider ionos.
The actual list in the gui is not showing me the ionos entry.
The underlying ACME client  use (acme.sh) support my provider ionos. Wild card certificate can be easily created.
The gui in opnsense is not showing up those ionos entry.

**Describe the solution you'd like**
I contacted the Let`s encrypt support. They told me opnsense is supporting ionos. Opnsense only have to update the gui.

**Describe alternatives you've considered**
Every other way are welcome.

**Comment by fraenki** [comment] 2021-06-29 09:31
Duplicate of #2345

**Closed by fraenki** 2021-06-29 09:31 UTC
