### ISSUE TITLE
net/haproxy: Maintenance tab keeps "loading"

### ISSUE THREAD

**Issue by sunib** [opnsense/plugins#2522] opened 2021-09-06 14:38 UTC
I'm a new user of haproxy plugin and noticed that the Maintenance tab keeps saying "Loading" instead of showing the status of my setup.

I'm using the stable latest versions:
* os-haproxy: 3.4
* OPNSense 21.7.1 (commit ec466867c)

**To Reproduce**
Install the `os-haproxy` plugin
Add some sites and make sure it's running like expected.
Click the `Maintenance`
I would expect a filled table with some information about my instances.

**Screenshots**
![image](https://user-images.githubusercontent.com/1828380/132232787-36c10227-c950-48dc-bb37-3361a1d1f1fd.png)

**Relevant log files**
```
[2ed400c0-a479-4cf6-b07c-12cccb911a67] Script action failed with Command '/usr/local/opnsense/scripts/OPNsense/HAProxy/socketCommand.py show-servers --output bootstrap --page-rows '10' --page '1' --search '' --sort-col '' --sort-dir ''' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 478, in execute subprocess.check_call(script_command, env=self.config_environment, shell=True, File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/OPNsense/HAProxy/socketCommand.py show-servers --output bootstrap --page-rows '10' --page '1' --search '' --sort-col '' --sort-dir ''' returned non-zero exit status 1.
```

This is what is dumped into the Chrome Console (I found that the JSON is an empty string `""`):
```
VM1323:1 Uncaught SyntaxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.success (jquery.bootgrid.js?v=17d0adcd1fef9573:232)
    at c (jquery-3.5.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.5.1.min.js:2)
    at l (jquery-3.5.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.5.1.min.js:2)
```

**Additional context**
I also tried this in a new installation and noticed the same behavior.

**Comment by fraenki** [comment] 2021-09-06 15:20
Duplicate of #2485

**Closed by fraenki** 2021-09-06 15:20 UTC
