### ISSUE TITLE
Zabbix Agent, "EnableRemoteCommands" has be deprecated

### ISSUE THREAD

**Issue by Taomyn** [opnsense/plugins#2231] opened 2021-02-11 07:33 UTC
**Describe the bug**
During startup the warning _"EnableRemoteCommands" has been deprecated_ is shown

**To Reproduce**
1. Install Zabbix Agent
2. Enable along with option "Enable Remote Commands"
3. Restart firewall

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/4365929/107611116-8bdc2080-6c43-11eb-99cb-c055f3023ce3.png)

**Environment**
OPNsense 21.1.1-amd64
FreeBSD 12.1-RELEASE-p13-HBSD
OpenSSL 1.1.1i 8 Dec 2020
![image](https://user-images.githubusercontent.com/4365929/107611189-b75f0b00-6c43-11eb-8ece-f5f17de0639d.png)

**Comment by fraenki** [comment] 2021-02-12 09:36
Duplicate of #1978

**Closed by fraenki** 2021-02-12 09:36 UTC
