### ISSUE TITLE
dns/dyndns: Namecheap update error: "parser error : Document labelled UTF-16 but has UTF-8 content"

### ISSUE THREAD

**Issue by shonjir** [opnsense/plugins#2666] opened 2021-11-25 01:24 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
I am currently running os-dyndns 1.26.  I use this plugin to perform dynamic dns update on my WAN interface via Namecheap.  Sometime around the 2.7.5 upgrade the dynamic DNS updates began failing with "parser error : Document labelled UTF-16 but has UTF-8 content".

The error references phpDynDNS.inc line 1502 which contains the following code:

```
            case 'namecheap':
                $tmp = str_replace("^M", "", $data);
```

This is old code, but it looks something changed recently to begin erroring on the quoted ^M in the code.  Unfortunately these errors are not being logged to syslog so I have no way of knowing exactly when the errors began.

**To Reproduce**
1. Configure namecheap as a dynamic DNS provider
2. Perform a dynamic DNS update
3. Observe the error report in the dashboard

**Expected behavior**
A crash report is not generated.  The dynamic DNS updates properly.

**Screenshots**
<img width="1146" alt="Screen Shot 2021-11-24 at 5 08 23 PM" src="https://user-images.githubusercontent.com/11600703/143334221-b8b1ec07-2e7d-4bfc-98eb-109e6500da18.png">

**Relevant log files**
```
[23-Nov-2021 08:03:31 America/Los_Angeles] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Document labelled UTF-16 but has UTF-8 content in /usr/local/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc on line 1502
[23-Nov-2021 08:03:31 America/Los_Angeles] PHP Warning:  simplexml_load_string():  in /usr/local/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc on line 1502
[23-Nov-2021 08:03:31 America/Los_Angeles] PHP Warning:  simplexml_load_string():                                      ^ in /usr/local/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc on line 1502
```

**Additional context**

**Environment**
User-Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
FreeBSD 12.1-RELEASE-p21-HBSD #0  1c99b63a2ba(stable/21.7)-dirty: Wed Nov 10 11:17:14 CET 2021     root@sensey:/usr/obj/usr/src/amd64.amd64/sys/SMP amd64
OPNsense 21.7.5 c279b7529
Plugins os-api-backup-1.0_1 os-chrony-1.4 os-dyndns-1.26 os-etpro-telemetry-1.5 os-mdns-repeater-1.0_1 os-ntopng-1.2_1 os-postfix-1.20 os-redis-1.1_1 os-sensei-1.10 os-sensei-agent-1.10.4 os-sensei-updater-1.10 os-smart-2.2 os-sunnyvalley-1.2_1 os-theme-cicada-1.28 os-theme-vicuna-1.4 os-upnp-1.4_2 os-vnstat-1.3 
Time Wed, 24 Nov 2021 16:49:41 -0800
OpenSSL 1.1.1l  24 Aug 2021
PHP 7.4.25

**Comment by fichtner** [comment] 2021-11-25 07:33
Discussion on forum: https://forum.opnsense.org/index.php?topic=25653.0

What happens when you remove the strange replace call and give $data directly to simple xml function?

**Comment by fichtner** [comment] 2021-11-25 12:11
@shonjir can you try this patch? 4b3abbf

    # opnsense-patch 4b3abbf


Cheers,
Franco

**Comment by shonjir** [comment] 2021-11-25 16:16
Update executes without issue after applying patch using

`# opnsense-patch -c plugins 4b3abbf`

Logs:

```
2021-11-25T08:11:35 | php-cgi[57318] | /services_dyndns_edit.php: Dynamic DNS: (Success) IP Address Updated Successfully! |  
-- | -- | -- | --
2021-11-25T08:11:35 | php-cgi[57318] | /services_dyndns_edit.php: Dynamic DNS: updating cache file /var/cache/dyndns_wan_@.<REDACTED>.com_0.cache: <REDACTED> |  
2021-11-25T08:11:35 | php-cgi[57318] | /services_dyndns_edit.php: Dynamic DNS (@.<REDACTED>.com): <REDACTED> extracted |  
2021-11-25T08:11:35 | php-cgi[57318] | /services_dyndns_edit.php: Dynamic DNS (@.<REDACTED>.com): Current Service: namecheap |  
2021-11-25T08:11:35 | php-cgi[57318] | /services_dyndns_edit.php: Dynamic DNS (@.<REDACTED>.com): _checkStatus() starting. |  
2021-11-25T08:11:35 | php-cgi[57318] | /services_dyndns_edit.php: Dynamic DNS (@.<REDACTED>.com via Namecheap): _update() starting. |  
2021-11-25T08:11:35 | php-cgi[57318] | /services_dyndns_edit.php: Dynamic DNS (@.<REDACTED>.com): running dyndns_failover_interface for wan. found igb1 |  
2021-11-25T08:11:35 | php-cgi[57318] | /services_dyndns_edit.php: Dynamic DNS (@.<REDACTED>.com): <REDACTED> extracted |  
2021-11-25T08:11:35 | php-cgi[57318] | /services_dyndns_edit.php: Dynamic DNS: updatedns() starting

```

**Comment by fichtner** [comment] 2021-11-25 18:44
@shonjir thanks, it's been reported to NameCheap here https://www.reddit.com/r/NameCheap/comments/qz1mjf/namecheap_dynamic_dns_returning_utf16_encoded/hljqzja/

**Comment by shonjir** [comment] 2021-11-25 18:52
Awesome, thank you so much for your help in figuring this out!  It was completely non-obvious to me that this was an upstream issue.

**Comment by fichtner** [comment] 2021-11-25 18:57
Sure no problem. We will see what happens and worst case we can carry the patch in the next release if the issue persists.


Cheers,
Franco

**Comment by freeman412** [comment] 2021-11-28 08:20
Than you! I was wondering if I had an issue, but now I know exactly what was going wrong!

**Comment by nblomquist** [comment] 2021-12-02 19:20
Thanks @fichtner . The patch worked for me too! The reddit responses from namecheap don't make it sound like this will be fixed on their end anytime soon. Hopefully this patch can just be applied in the next release of opnsense plugins.

Thanks again!

**Comment by fichtner** [comment] 2021-12-02 19:23
@nblomquist the problem is if we ship this and they repair it it’s going to be broken for us again…

**Comment by nblomquist** [comment] 2021-12-02 19:30
I don't think anything will break since the patch searches for `utf-16` and replaces it with `utf-8`. That means if `utf-16` is NOT found nothing happens, right? `utf-8` will just remain in the file as sent.

It will break I suppose if they (namecheap) actually start sending a real `utf-16` encoded file with `utf-16` characters. But I don't think that will happen. (I am probably wrong though)

**Comment by fichtner** [comment] 2021-12-02 20:35
Assuming they do UTF-16 for a specific reason the second scenario is more probable and indeed problematic. 😊

**Comment by fichtner** [comment] 2021-12-09 13:16
Workaround was shipped for better or worse. Closing until something changes on their end...

**Closed by fichtner** 2021-12-09 13:16 UTC
Labels: upstream
