### ISSUE TITLE
net/haproxy: arbitrary sort order of ModelRelationField items

### ISSUE THREAD

**Issue by billyburly** [opnsense/plugins#582] opened 2018-03-05 16:06 UTC
There is no way to control the ordering of rules/actions. This is incredibly important, especially if implementing http2. The actions seem to be put into the config in a random order.

**Comment by billyburly** [comment] 2018-05-24 19:37
This bug still exists after the fix you mentioned, running 18.1.8. This is a regression/bug, not an enhancement. In the previous haproxy interface (the one that came from the pfsense lineage of code) you had control over the order of the rules.

Before saving (notice the rule that starts with 999 is at the end). This is from the edit page for a public service.:
![image](https://user-images.githubusercontent.com/741241/40509544-e3709934-5f67-11e8-97c9-c4579882d8b6.png)

After saving (now its in the middle):
![image](https://user-images.githubusercontent.com/741241/40509565-f43d1cf6-5f67-11e8-9483-67ca718d171b.png)

Also note that this method (if it worked) of controlling the ordering of rules is only really usable for trivial cases. There is no way to reorder the entries in the rules box. So if you are using anything more then a couple rules it becomes very tedious and unusable as you are required to rebuild the list up to the point you want to change.

**Comment by billyburly** [comment] 2018-05-24 19:41
This was caused by some change related to https://github.com/opnsense/plugins/issues/208

**Comment by fraenki** [comment] 2018-05-24 19:42
> This is a regression/bug, not an enhancement. In the previous haproxy interface (the one that came from the pfsense lineage of code)

It's not a regression, because the HAProxy plugin has been written from scratch, no pfSense plugin code exists in OPNsense.

**Comment by fraenki** [comment] 2018-05-24 19:44
> This was caused by some change related to #208

Nope.

**Comment by fraenki** [comment] 2018-05-24 19:47
Note that I said the fix will be available in OPNsense 18.**7**.

**Comment by billyburly** [comment] 2018-05-24 19:49
Sorry for the misunderstanding. I thought since this started out as a fork of pfsense things originally came from there at some point. So its more of a feature lost with the new code.

Also was confused with the release of 18.1.7, didn't realize you meant something different.

**Comment by billyburly** [comment] 2018-08-15 03:53
Ok, finally tested on 18.7.1. Still unable to order the rules

**Comment by fraenki** [comment] 2018-08-15 21:28
@AdSchellevis, @ghostwheel42: Let's move the discussion to this issue.

@AdSchellevis wrote in https://github.com/opnsense/plugins/issues/769#issuecomment-413111958:

> @ghostwheel42 I'm not 100% we're looking at the same case, but I checked "Public Services" and traced the rules there, they use a ModelRelationField which is isn't (and never was) sorted by the order in the selectbox.
> 
> So... if we're looking at the same field/type, I'm afraid @fraenki made the false assumption that those are ordered by input and this is actually a bug in the HAProxy plugin. I'm not sure why ordering matters here, but if it does and needs the field type that's in there now, I can't fix it at the moment.
> 
> for reference : https://github.com/opnsense/core/blob/18.7.1/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/ModelRelationField.php#L196-L203

Indeed, I was always assuming that these fields are ordered by input. And in most cases this seems to be true, I'm heavily relying on the sort order and it seems to never change on my existing setups.

I can't find a way to properly reproduce this, what are you doing that messes up the sort order?

> maybe a weight on the rule could be an easy fix to achieve the desired behaviour, but that's just a possible solution for the issue. maybe it's better to open a new feature request and discuss with @fraenki

I don't like this aproach. It's clumsy. This is not something that the use should solve by specifying a "priority", but instead the GUI should allow sorting. Has anyone ideas for a more sophisticated solutions? Maybe add some sorting attributes to ModelRelationField?

**Comment by fraenki** [comment] 2018-08-15 21:30
refs #725

**Comment by ghostwheel42** [comment] 2018-08-23 09:38
@franki: Hi, and sorry for the late answer.

You are correct: Nothing messes up the sort order.
But you can't re-order rules, after creation. Rules always remain in creation order. If you want to reorder, you have to delete and recreate the rule.
The rules seem to have an implicit "weight" (the creation time).

So I think this issue is an enhancement request and not a bug. There should be an re-orderable input to put rules in the order you want (drag and drop?). It also could be used for certificates, as the first one will be used in non strict-sni setups as default.

**Comment by fraenki** [comment] 2018-08-23 13:26
@ghostwheel42 Thanks for the clarification! @fichtner suggested to use a tokenizer2 feature for this:
https://github.com/zellerda/Tokenize2/blob/eaf04ff2468dbd2d876f946860d73675eb93c098/tokenize2.js#L85

Any idea how to properly make this configurable in the OPNsense MVC framework? Because I don't :)

**Comment by fichtner** [comment] 2018-08-23 15:51
It requires an unfortunately stale library called „jquery ui“ to work. If it worked it would probably be ok as on for all current  fields. I don’t see a problem in reordering. Cc @adschellevis what do you think about this dependency?

**Comment by AdSchellevis** [comment] 2018-08-23 18:36
@fichtner I rather keep jQuery UI out, it wouldn't solve the issue anyway since the order isn't determined by the selected items in the list anyway.

**Comment by fichtner** [comment] 2018-08-23 19:04
For ordering model relations, yep.

**Comment by AdSchellevis** [comment] 2018-12-06 10:23
@fraenki I've created an issue/question for you here https://github.com/dragonofmercy/Tokenize2/issues/62, we will pickup the model code to support ordering at our end. That's basically all I can do for you at the moment.

**Comment by fraenki** [comment] 2019-01-10 11:21
@AdSchellevis A fix was comitted upstream. I'd love to get this done for an early 19.1.x release. What are the next steps? Merge the new tokenize2 version?

**Comment by AdSchellevis** [comment] 2019-01-10 12:53
@fraenki Probably pull in the new version (when available) and adjust our template, if you create an issue in core, I’ll try to look at this at the end of next week.

**Comment by fraenki** [comment] 2019-02-25 22:05
This will be fixed in the upcoming release os-haproxy 2.15. Thanks to Ad!

**Closed by fraenki** 2019-02-25 22:05 UTC
Labels: feature, help wanted

**Comment by DiegoQueiroz** [comment] 2019-02-26 17:06
@fraenki What happens to existing rules? The current order will remain unchanged?

I need to upgrade an production server with several rules (which is a pain to maintain without this feature), but I am worried about the side effects.

**Comment by fraenki** [comment] 2019-02-26 17:10
> What happens to existing rules? The current order will remain unchanged?

It will remain unchanged. At least according to my own testing... :)
