### ISSUE TITLE
Quagga: statistics and diagnostics page (done); follow ups

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#118] opened 2017-04-12 19:43 UTC
I'd like to have some kind of diagnostics within the Routing tab. 

E.g. for OSPF it would be very cool to show the output of commands like "sh ip ospf neighbor" or the fib routing table. Also with bgp a show ip bgp summary or advertised routes would be cool.

If you guys know a page which I can use as a template with similar function I could try to do it on my own.

**Comment by fabianfrz** [comment] 2017-04-13 14:16
@mimugmail you need to provide an API controller, which you can use to query the information, a script which will serve the data as well as an action in the frontend with a template.

You will need to add an action to this file:
https://github.com/opnsense/plugins/blob/master/net/quagga/src/opnsense/service/conf/actions.d/actions_quagga.conf
This will allow you to run a script via configd.
The script itself should be in any programming language, OPNsense supports. The core team prefers something like shell or python. Ruby can be used as a dependency. Perl is available too. The script should return a JSON data structure.

The API controller looks like this one for example: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/DiagnosticsController.php

For the UI controller I do not have any hints as this is always specific to the plugin.

**Comment by mimugmail** [comment] 2017-04-13 21:10
@fabianfrz Thanks! I'll start with a new PR when the new version is released.

**Comment by mimugmail** [comment] 2017-04-18 10:59
@fabianfrz Design question: Should I create a general diagnostics page under the protocols, or on every protocol configuraion page some diagnostics buttons?

ATM: I have sh script for bgp which can be copied and modified for every protocol
https://github.com/mimugmail/plugins/blob/master/net/quagga/src/opnsense/scripts/quagga/diag-bgp.sh

I'd pass the arguments via the actions_quagga.conf (if possible):
https://github.com/mimugmail/plugins/blob/master/net/quagga/src/opnsense/service/conf/actions.d/actions_quagga.conf

**Comment by fabianfrz** [comment] 2017-04-18 11:05
@mimugmail I would make an extra menu entry for diagnostics like it is everywhere else in the menu so it is consistent.

All diagnostic things could be on the same page (one diagnostics page) or separate (whatever makes more sense).

For the config file: you can also pass though parameters if your like or it is easier to you.

**Comment by fichtner** [comment] 2017-04-30 13:00
Close this one?

I'm probably very late to the party, but we really need to change the menu location, right now it looks like quagga is a core routing service, but we don't have a core routing service in the core...

Items belong under Services: Quagga

**Comment by fabianfrz** [comment] 2017-04-30 13:57
@fichtner Good question - there are still some diagnostics views to add - it is a very large To Do. The most important ones are there now (maybe use a follow up ticket for extension)

For the menu: This was intended to look like this as the menu currently looks like it contains 2 to 7 in the OSI Model so I have added it to layer 3-4 which did not exist until now :)
If you thing it is better placed in Services, you can place it there.

**Comment by mimugmail** [comment] 2017-04-30 17:54
I don't really see this as a "Service". Only guys who know what they do install Quagga.

**Comment by fabianfrz** [comment] 2017-04-30 19:10
Maybe also a mix could be used: move `Routing > *` to `Routing > Quagga > *`, Then move the routing stuff of core into `Routing` - like `static routes`. If it is called `Networking`, also `ARP` or `NDP` could be in the menu.

**Comment by fichtner** [comment] 2017-05-01 11:47
Ok.. I like the Routing / Quagga layout. But the (empty) Routing menu needs to be anchored in the core. We'd want to move more things there, but that also requires further menu tinkering we may be able to do for 17.7 or 18.1.

**Comment by mimugmail** [comment] 2017-05-03 14:53
@fabianfrz I installed the latest master now and checked the Diagnostics. For BGP the first tab is the responsive output from quagga.rb and the second one just text. Is this going to be updated in some time or will you allow a mix of it? 
Second Q: How would you handle a command referenced to a specific neighbor? Create a html form and typing the neighbor IP by hand or automagic create a tab for every neighbor?

**Comment by fabianfrz** [comment] 2017-05-03 15:52
At least it should be in the matching tab. If you need an IP address input and a button, you should add that to the tab and add a container for the content. There is currently not really a "standard way" to do it.

For the first question: I hope it will some day. At the moment it is better than nothing (you are talking about your code ;) ). I don't have much time now as I am out of time now. Note that OSPF will always have a higher priority and it is still not finished. For giving the parameter to the backend you should be able to use the post part in ajaxcall ("{}")

**Comment by mimugmail** [comment] 2017-05-24 20:01
@fabianfrz Do you think you can add a button to the general diagnostics view to dump the complete quagga configuration (via vtysh -c "show run" or something)? Perhaps with some of your ruby magic? 

A user always working via CLI and switching to GUI might feel better to see what the changed did to the running-config.

**Comment by fabianfrz** [comment] 2017-05-24 20:48
There is no ruby required - if you want to dump the configuration file the best way is a pass through as I don't see an advantage by parsing it (the advantage is that the headings can be formatted differently).

Is it worth it anyway?

**Comment by mimugmail** [comment] 2017-05-25 04:55
For me a plain dump in text is just fine. I can try this next week when I'm back at the office.

**Comment by mimugmail** [comment] 2017-05-25 05:29
Ok, this is really easy .. when all PRs are in I'll push some lines for this one.

Sadly I called the bash script diag-bgp.sh, but a show run is global, so this doesn't fit perfectly :(

**Comment by fabianfrz** [comment] 2017-05-25 06:49
you can rename the file or write the command directly into the configuration file. #166 is not affected as it is to the stable (release) branch (you probably want to contribute to master)

**Comment by mimugmail** [comment] 2017-05-25 09:25
I'll try this, thanks. 
I always pull against master and let you guys decide what goes into stable :)

**Comment by fabianfrz** [comment] 2017-05-25 12:08
@mimugmail It would be better if you decide when to call your stuff stable.

**Comment by mimugmail** [comment] 2017-05-25 13:09
PR #167 is stable! But it requires 3 patches to the core, so @fichtner has to decide if this goes into the next or whatever stable.

**Comment by fabianfrz** [comment] 2017-05-25 14:00
If the core stuff goes to release we can put that to master (`os-quagga-devel`) and release it at least one release later. If not, it may last until `17.7`

I made a new stable version without all the new BGP stuff (no routemaps etc.) but all the diagnostics stuff is in as well as OSPFv3. So you may have to wait. If @fichtner says your commit is ok, anyone with write permissions can merge it.

**Comment by fichtner** [comment] 2017-05-25 15:13
Routemaps can go to master, os-quagga-devel should be used with opnsense-devel. Both are for testing so I don't see how we should wait. If os-quagga-devel doesn't work, people can fall back to os-quagga. And the relevant change only limits the selector, it would work on opnsense package too. Go for it. 😊

**Comment by fabianfrz** [comment] 2017-07-23 10:50
I think this is already fixed

**Closed by fabianfrz** 2017-07-23 10:50 UTC
