### ISSUE TITLE
os-mdns-repeater Fails To Start When Carp Failover Enabled

### ISSUE THREAD

**Issue by dkanzlemar** [opnsense/plugins#3298] opened 2023-02-05 21:13 UTC
When I try and enable mDNS Repeater Plugin, if I have the "Enable CARP Failover" checkbox checked, the service will not start. In the logs, I get the following 2 warnings:

1) /usr/local/etc/rc.d/mdns-repeater: WARNING: failed precmd routine for mdns_repeater
2) /usr/local/etc/rc.d/mdns-repeater: WARNING: /var/run/mdns-repeater.CARP_MASTER is not readable.

If I turn on the mDNS Repeater without that option, it starts, but things like my wireless stop working due to it repeating across my MASTER and BACKUP nodes. To work around, I am turning the mDNS Repeater on on on my MASTER node, and off entirely on the BACKUP node. It doesn't allow for High Availability with mDNS, but keeps my network up.

Below is the information I have for my use:
- Current Plugin Name: os-mdns-repeater
- Current Plugin Version: 1.1
- Last version where bug did not exist: Unknown
- URI of the GUI page: /ui/mdnsrepeater
- Steps to reproduce: 1) Enable mDNS Repeater. 2) Select at least 2 Listen Interfaces. 3) Click "Enable Carp Failover" checkbox. 4) Click Save.
- OPNsense Version: 23.1_6

Please let me know if you need me to provide any more information.

**Comment by fichtner** [comment] 2023-02-05 21:58
I’m unsure what the problem is as the things you describe are what they are supposed to do. It could help to get ifconfig of your cluster carp interfaces. It looks like it’s not set up as it should.

**Comment by dkanzlemar** [comment] 2023-02-05 22:37
Sure thing. Here is my setup when I boot the server and my output of ifconfig. I completely shut down the second node and tried to just enable the failover option on the running node, but still get the same issue. Here is my output (note that interfaces igc2 and igc3 don't use CARP):

 LAN (igc1)      -> v4: 10.0.7.2/24
 MAN (igc3)      -> v4: 10.0.1.2/24
 PFSYNC (igc2)   -> v4: 10.0.10.2/24
 VLAN_16_GUEST (vlan01) -> v4: 10.0.16.2/24
 VLAN_20_WIFI (vlan02) -> v4: 10.0.20.2/24
 VLAN_22_IOT (vlan03) -> v4: 10.0.22.2/24
 VLAN_23_STREAMING (vlan04) -> v4: 10.0.23.2/24
 VLAN_27_SERVICES (vlan05) -> v4: 10.0.27.2/24
 VLAN_29_BACKUPS (vlan06) -> v4: 10.0.29.2/24
 VLAN_40_WORK (vlan07) -> v4: 10.0.40.2/24
 VLAN_53_ADGUARD (vlan010) -> v4: 10.0.53.2/24
 VLAN_67_SURVEILLANCE (vlan08) -> v4: 10.0.67.2/24
 VLAN_97_SERVER (vlan09) -> v4: 10.0.97.2/24
 WAN (igc0)      -> v4: 10.0.0.2/24
 
 
 igc0: flags=8963<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: WAN (wan)
        options=4802028<VLAN_MTU,JUMBO_MTU,WOL_MAGIC,NOMAP>
        ether 00:e2:69:58:05:73
        inet 10.0.0.2 netmask 0xffffff00 broadcast 10.0.0.255
        inet 10.0.0.10 netmask 0xffffffff broadcast 10.0.0.10 vhid 1
        carp: MASTER vhid 1 advbase 1 advskew 0
        media: Ethernet autoselect (2500Base-T <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
igc1: flags=8963<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: LAN (lan)
        options=4802028<VLAN_MTU,JUMBO_MTU,WOL_MAGIC,NOMAP>
        ether 00:e2:69:58:05:74
        inet 10.0.7.2 netmask 0xffffff00 broadcast 10.0.7.255
        inet 10.0.7.1 netmask 0xffffffff broadcast 10.0.7.1 vhid 7
        carp: MASTER vhid 7 advbase 1 advskew 0
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
igc2: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: PFSYNC (opt11)
        options=4802028<VLAN_MTU,JUMBO_MTU,WOL_MAGIC,NOMAP>
        ether 00:e2:69:58:05:75
        inet 10.0.10.2 netmask 0xffffff00 broadcast 10.0.10.255
        media: Ethernet autoselect (10baseT/UTP <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
igc3: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: MAN (opt12)
        options=4802028<VLAN_MTU,JUMBO_MTU,WOL_MAGIC,NOMAP>
        ether 00:e2:69:58:05:76
        inet 10.0.1.2 netmask 0xffffff00 broadcast 10.0.1.255
        media: Ethernet autoselect
        status: no carrier
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x5
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
enc0: flags=0<> metric 0 mtu 1536
        groups: enc
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
pfsync0: flags=41<UP,RUNNING> metric 0 mtu 1500
        pfsync: syncdev: igc2 syncpeer: 10.0.10.3 maxupd: 128 defer: off
        syncok: 1
        groups: pfsync
pflog0: flags=20100<PROMISC,PPROMISC> metric 0 mtu 33160
        groups: pflog
vlan01: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: VLAN_16_GUEST (opt1)
        options=4000000<NOMAP>
        ether 00:e2:69:58:05:74
        inet 10.0.16.2 netmask 0xffffff00 broadcast 10.0.16.255
        inet 10.0.16.1 netmask 0xffffffff broadcast 10.0.16.1 vhid 16
        groups: vlan
        carp: MASTER vhid 16 advbase 1 advskew 0
        vlan: 16 vlanproto: 802.1q vlanpcp: 0 parent interface: igc1
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
vlan010: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: VLAN_53_ADGUARD (opt10)
        options=4000000<NOMAP>
        ether 00:e2:69:58:05:74
        inet 10.0.53.2 netmask 0xffffff00 broadcast 10.0.53.255
        inet 10.0.53.1 netmask 0xffffffff broadcast 10.0.53.1 vhid 53
        groups: vlan
        carp: MASTER vhid 53 advbase 1 advskew 0
        vlan: 53 vlanproto: 802.1q vlanpcp: 0 parent interface: igc1
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
vlan02: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: VLAN_20_WIFI (opt2)
        options=4000000<NOMAP>
        ether 00:e2:69:58:05:74
        inet 10.0.20.2 netmask 0xffffff00 broadcast 10.0.20.255
        inet 10.0.20.1 netmask 0xffffffff broadcast 10.0.20.1 vhid 20
        groups: vlan
        carp: MASTER vhid 20 advbase 1 advskew 0
        vlan: 20 vlanproto: 802.1q vlanpcp: 0 parent interface: igc1
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
vlan03: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: VLAN_22_IOT (opt3)
        options=4000000<NOMAP>
        ether 00:e2:69:58:05:74
        inet 10.0.22.2 netmask 0xffffff00 broadcast 10.0.22.255
        inet 10.0.22.1 netmask 0xffffffff broadcast 10.0.22.1 vhid 22
        groups: vlan
        carp: MASTER vhid 22 advbase 1 advskew 0
        vlan: 22 vlanproto: 802.1q vlanpcp: 0 parent interface: igc1
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
vlan04: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: VLAN_23_STREAMING (opt4)
        options=4000000<NOMAP>
        ether 00:e2:69:58:05:74
        inet 10.0.23.2 netmask 0xffffff00 broadcast 10.0.23.255
        inet 10.0.23.1 netmask 0xffffffff broadcast 10.0.23.1 vhid 23
        groups: vlan
        carp: MASTER vhid 23 advbase 1 advskew 0
        vlan: 23 vlanproto: 802.1q vlanpcp: 0 parent interface: igc1
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
vlan05: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: VLAN_27_SERVICES (opt5)
        options=4000000<NOMAP>
        ether 00:e2:69:58:05:74
        inet 10.0.27.2 netmask 0xffffff00 broadcast 10.0.27.255
        inet 10.0.27.1 netmask 0xffffffff broadcast 10.0.27.1 vhid 27
        groups: vlan
        carp: MASTER vhid 27 advbase 1 advskew 0
        vlan: 27 vlanproto: 802.1q vlanpcp: 0 parent interface: igc1
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
vlan06: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: VLAN_29_BACKUPS (opt6)
        options=4000000<NOMAP>
        ether 00:e2:69:58:05:74
        inet 10.0.29.2 netmask 0xffffff00 broadcast 10.0.29.255
        inet 10.0.29.1 netmask 0xffffffff broadcast 10.0.29.1 vhid 29
        groups: vlan
        carp: MASTER vhid 29 advbase 1 advskew 0
        vlan: 29 vlanproto: 802.1q vlanpcp: 0 parent interface: igc1
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
vlan07: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: VLAN_40_WORK (opt7)
        options=4000000<NOMAP>
        ether 00:e2:69:58:05:74
        inet 10.0.40.2 netmask 0xffffff00 broadcast 10.0.40.255
        inet 10.0.40.1 netmask 0xffffffff broadcast 10.0.40.1 vhid 40
        groups: vlan
        carp: MASTER vhid 40 advbase 1 advskew 0
        vlan: 40 vlanproto: 802.1q vlanpcp: 0 parent interface: igc1
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
vlan08: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: VLAN_67_SURVEILLANCE (opt8)
        options=4000000<NOMAP>
        ether 00:e2:69:58:05:74
        inet 10.0.67.2 netmask 0xffffff00 broadcast 10.0.67.255
        inet 10.0.67.1 netmask 0xffffffff broadcast 10.0.67.1 vhid 67
        groups: vlan
        carp: MASTER vhid 67 advbase 1 advskew 0
        vlan: 67 vlanproto: 802.1q vlanpcp: 0 parent interface: igc1
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
vlan09: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: VLAN_97_SERVER (opt9)
        options=4000000<NOMAP>
        ether 00:e2:69:58:05:74
        inet 10.0.97.2 netmask 0xffffff00 broadcast 10.0.97.255
        inet 10.0.97.1 netmask 0xffffffff broadcast 10.0.97.1 vhid 97
        groups: vlan
        carp: MASTER vhid 97 advbase 1 advskew 0
        vlan: 97 vlanproto: 802.1q vlanpcp: 0 parent interface: igc1
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>

**Comment by fichtner** [comment] 2023-02-06 07:09
I don't see any problem here either. I'd enable CARP mode on both members and reboot master. Backup should activate (including mdns-repeater service) and when master is back all goes to master...


Cheers,
Franco

**Comment by dkanzlemar** [comment] 2023-02-06 13:26
Son of a... I didn't think to try a reboot after enabling the option! That absolutely did the trick! Thank you for pointing me in the right direction there. It took a reboot of both nodes to get things to completely work, but all is well now! Thank you again!

**Comment by sorano** [comment] 2023-02-11 09:08
@dkanzlemar So close the issue then?

**Comment by dkanzlemar** [comment] 2023-02-11 14:45
Yes. Sorry, I didn’t realize I had the ability to close it myself. Should be closed now.

**Closed** 2023-02-11 14:45 UTC
Labels: support
