### ISSUE TITLE
dyndns: Cloudfare Password Information

### ISSUE THREAD

**Issue by tfserra** [opnsense/plugins#1533] opened 2019-10-06 17:36 UTC
Hi,

When using the Dynamic DNS with cloudflare, I think it would be good to have in the information of the password something like "Cloudfare use Global API Key from API Keys".

I was setting this and couldn't understand why it wasn't working with the normal password. Only by chance, I tried the api key and it worked.

Thanks

**Comment by dpieski** [comment] 2019-10-29 19:46
Duplicate of #1045

**Closed** 2019-10-30 07:39 UTC
