### ISSUE TITLE
net/haproxy: HAProxy config peers fails to declare the local peer

### ISSUE THREAD

**Issue by nzkiwi68** [opnsense/plugins#3114] opened 2022-09-07 01:53 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
Service: HAProxy:Settings:Peers

There is the concept of:
- Peer 1 (this host)
- Peer 2 (remote host)

This is used to propagate entries of any data-types in stick-tables between several HAProxy instances over TCP connections.

The issue is, on HA sync from primary/master to the backup firewall, the Peer 1 and Peer 2 data is synced exactly as it is entered in the primary firewall resulting in an unworkable configuration on the backup firewall.

**To Reproduce**
Create a HAProxy peer setup with a pair of HA OPNsense firewalls, sync the primary to the backup with the HAProxy settings set to sync via HA and see that exactly the same Peer 1 and Peer 2 is created in the backup firewall.

**Expected behavior**
Either:
Do NOT sync the peer data at all (less desireable)
 - or, better yet
During the HA sync script, transpose the Peer 1 and Peer 2 data, that is:
Write the Primary firewall Peer 1 data as entered into the HA backup Peer 2
Write the Primary firewall Peer 2 data as entered into the HA backup Peer 1

**Screenshots**
![HAProxy peers](https://user-images.githubusercontent.com/67399588/188771137-772618c5-1969-48e2-99c4-55aaf4c35c4a.jpg)

**Relevant log files**
none

**Environment**
OPNsense 22.7.2 (amd64, OpenSSL).
Intel(R) Atom(TM) CPU C2758 @ 2.40GHz (8 cores, 8 threads)

**Comment by fraenki** [comment] 2022-09-07 08:40
> resulting in an unworkable configuration on the backup firewall

Could you please elaborate more on this? How exactly is this an unworkable configuration? Do you get any error messages or unexpected behaviour?

AFAICT, this is exactly how peers should be configured:
http://cbonte.github.io/haproxy-dconv/2.4/configuration.html#3.5

**Comment by nzkiwi68** [comment] 2022-09-07 23:11
Thanks for your answer. I'll try and elaborate more.

The issue is when you are running a HA pair of OPNsense firewalls setup as a primary/master and backup/slave.
Consider this simple example, I'm omitting a lot of detail that is not relevant for what I'm trying to explain, so no mention WAN interfaces, etc, just LAN and HAProxy.

Primary/master firewall LAN: 192.168.1.1 and firewall name: fw1.localdomain

Backup/slave firewall LAN: 192.168.1.2 and firewall name: fw2.localdomain

**High Availability Settings**
Inside the primary firewall, you setup HA sync and all that good stuff for a pair of HA firewalls, I'm not detailing how you do any of that, other than to say under:
`System: High Availability: Settings`
`HAProxy Load Balancer` is ticked to sync the HAProxy settings from the primary/master firewall to the backup/slave firewall

**HAProxy Settings**
Inside the primary firewall, you setup HAProxy peers.
`Services: HAProxy: Settings`
Now, you setup Peer 1 (this host)
Peer name (FQDN): fw1.localdomain
Listen address (IP): 192.168.1.1
TCP port: 1024

Now, you setup Peer 2 (remote host)
Peer name (FQDN): fw2.localdomain
Listen address (IP): 192.168.1.2
TCP port: 1024

**Here comes the issue.**
You then do `System: High Availability: Settings` Synchronize config to backup.
If you then logon to the backup firewall 192.168.1.2, HAProxy has set:
[https://192.168.1.2/ui/haproxy#general-peers](https://192.168.1.2/ui/haproxy#general-peers)
Peer 1 (this host)
Peer name (FQDN): fw1.localdomain
Listen address (IP): 192.168.1.1
TCP port: 1024

Peer 2 (remote host)
Peer name (FQDN): fw2.localdomain
Listen address (IP): 192.168.1.2
TCP port: 1024

### This is the issue. The backup/slave firewall should actually be:
Peer 1 (this host)
Peer name (FQDN): fw2.localdomain
Listen address (IP): 192.168.1.2
TCP port: 1024

Peer 2 (remote host)
Peer name (FQDN): fw1.localdomain
Listen address (IP): 192.168.1.1
TCP port: 1024

**Comment by nzkiwi68** [comment] 2022-09-07 23:18
I don't manually set the HAProxy backup firewall as shown above, then, the backup firewall HAproxy doesn't seem to listen on 192.168.1.2 TCP port 1024, I cannot see any incoming TCP states from 192.168.1.1 to the backup firewall 192.168.1.2 TCP dst 1024.

**Comment by nzkiwi68** [comment] 2022-09-07 23:39
More work after reading and re-reading [http://cbonte.github.io/haproxy-dconv/2.4/configuration.html#3.5](http://cbonte.github.io/haproxy-dconv/2.4/configuration.html#3.5)

Primary firewall HAProxy Config Export:
_peers opnsense-haproxy-peers
    peer fw1.localdomain 192.168.1.1:1024
    peer fw2.localdomain 192.168.1.2:1024_

But, on reading HAProxy documentation, don't we need to:
"It is strongly recommended to have the exact same peers declaration on all
peers and to only rely on the "-L" command line argument or the "[localpeer](http://cbonte.github.io/haproxy-dconv/2.4/configuration.html#localpeer)"
global configuration setting to change the local peer name. This makes it
easier to maintain coherent configuration files across all peers.:

So, shouldn't it look like this?
Primary fw:
_peers opnsense-haproxy-peers
    peer fw1.localdomain 192.168.1.1:1024 -L
    peer fw2.localdomain 192.168.1.2:1024_

Backup fw:
_peers opnsense-haproxy-peers
    peer fw1.localdomain 192.168.1.1:1024
    peer fw2.localdomain 192.168.1.2:1024 -L_

or, using the "localpeer" global configuration setting [http://cbonte.github.io/haproxy-dconv/2.4/configuration.html#localpeer](http://cbonte.github.io/haproxy-dconv/2.4/configuration.html#localpeer)

Primary fw:
Add a global declare option, pulling the system name of the firewall:
_global
    localpeer fw1.localdomain_

_peers opnsense-haproxy-peers
    peer fw1.localdomain 192.168.1.1:1024
    peer fw2.localdomain 192.168.1.2:1024_

Backup fw:
_global
    localpeer fw2.localdomain_

_peers opnsense-haproxy-peers
    peer fw1.localdomain 192.168.1.1:1024
    peer fw2.localdomain 192.168.1.2:1024_

**Comment by nzkiwi68** [comment] 2022-09-08 00:14
Tried passing in the Services: HAProxy: Settings, Global Parameters, Custom options:

`localpeer "$HOST"`


This would be perfect, as this will pull the environment variable of HOST which would then be able to be sync'd to the backup firewall. However, the GUI didn't allow this:

[NOTICE] (37245) : haproxy version is 2.4.18-1d80f18
[NOTICE] (37245) : path to executable is /usr/local/sbin/haproxy
[ALERT] (37245) : parsing [/usr/local/etc/haproxy.conf.staging:26] : 'localpeer' expects a name as an argument.
[ALERT] (37245) : Error(s) found in configuration file : /usr/local/etc/haproxy.conf.staging
[ALERT] (37245) : Fatal errors found in configuration.

According the HAProxy documentation, passing an environment variable in the global config section is valid.
[http://cbonte.github.io/haproxy-dconv/2.4/configuration.html#2.3](http://cbonte.github.io/haproxy-dconv/2.4/configuration.html#2.3)

**Comment by nzkiwi68** [comment] 2022-09-12 01:31
Any update please?

I don't think this is a support issue, but a code issue.

**Comment by fraenki** [comment] 2022-09-12 08:12
I'm just volunteering here, so I ask to you to be patient.

**Comment by nzkiwi68** [comment] 2022-09-12 19:26
Of course. No problem.

**Comment by nzkiwi68** [comment] 2022-09-26 02:13
HAPROXY needs to declare the local peer.

Primary fw:
Add a global declare option, pulling the system name of the firewall:
global
localpeer "$HOST"    (where $HOST is fw1.localdomain which in my example is the system name of the firewall)

peers opnsense-haproxy-peers
peer fw1.localdomain 192.168.1.1:1024
peer fw2.localdomain 192.168.1.2:1024

Backup fw:
global
localpeer "$HOST"    (where $HOST is fw2.localdomain which in my example is the system name of the firewall)

peers opnsense-haproxy-peers
peer fw1.localdomain 192.168.1.1:1024
peer fw2.localdomain 192.168.1.2:1024

**Comment by nzkiwi68** [comment] 2022-10-03 02:12
Any chance this issue can be looked at?

This is not a support issue, but, a coding issue for the plugin.

**Comment by fraenki** [comment] 2022-10-11 13:31
Thanks for providing detailed information and example configuration.

This should be fixed in https://github.com/opnsense/plugins/pull/3156/commits/247ce7f3b49da722923bb6a4ebaf6e2297778f86. The name of the peer is now automatically compared to the system hostname and if it matches, then the peer is configured as local peer.

You may try to test it:
```
opnsense-patch -c plugins 247ce7f3
```
(The patch may fail to apply, because there are other changes in this branch.)

**Closed by fraenki** 2022-10-11 13:31 UTC
Labels: support
