### ISSUE TITLE
www/nginx: IP ACL empty on nginx.conf

### ISSUE THREAD

**Issue by Oxima69** [opnsense/plugins#1363] opened 2019-06-08 12:15 UTC
With IP ACL defined and enabled in WebGUI, and assign it to a **Location**
there is only `# IP ACL` entry in the nginx.conf

**Comment by fabianfrz** [comment] 2019-06-09 10:27
It works on my machine - did you configure some rules?

**Comment by Oxima69** [comment] 2019-06-10 09:25
I don't understand your question exactly. (roll on what ?)
To the understanding ....when i set IP ACL on **HTTP Server** the entries are shown in the nginx.conf

**Comment by Szeraax** [comment] 2019-12-09 21:36
I also have this issue. I will attempt to find the root cause. 

I am using 19.1.10 (I just saw there is 19.7 available, I'll upgrade to latest ASAP and report back if bug is still present). 

I created a dummy IP ACL with default: deny and added an IP address to the allow list (e.g. `192.168.2.3`)
I created a dummy location for `/` and added the IP ACL to the location. (I tried both with and without a upstream assigned - same result each time)
I created a dummy http server and added the dummy location to it.
When I clicked "generate nginx.conf" from the UI, my resulting location does not have any entry under the IP ACL:
```
location  / {
    BasicRule wl:19;
    DeniedUrl "/waf_denied.html";
        # IP ACL
    autoindex off;
    http2_push_preload off;
    proxy_set_header Host $host;
    proxy_set_header X-TLS-Cipher $ssl_cipher;
    proxy_set_header X-TLS-Protocol $ssl_protocol;
    proxy_set_header X-TLS-SNI-Host $ssl_server_name;
    # proxy headers for backend server
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-TLS-Client-Intercepted $tls_intercepted;
    proxy_ignore_client_abort off;
    proxy_request_buffering on;
    proxy_max_temp_file_size 1024m;
    proxy_buffering on;
    proxy_pass http://upstreamd2be59635f4b4474865ac9e8f358e745;
    proxy_hide_header X-Powered-By;
```

**Comment by fabianfrz** [comment] 2019-12-10 16:16
can you run configctl template reload OPNsense/Nginx on cli to see if it has an error?

**Comment by Oxima69** [comment] 2020-01-05 16:13
```
root@ah-fw-01:/ # configctl template reload OPNsense/Nginx
OK

```
Still the issue.....

```
location  /api {
    BasicRule wl:19;
    DeniedUrl "/waf_denied.html";
        # IP ACL
    autoindex off;
    http2_push_preload off;
    proxy_set_header Host $host;
```

**Comment by Szeraax** [comment] 2020-01-05 16:23
I have added my IP ACL to any location again and ran that command. Gives no error, says "OK" as only output. IP ACL actually has an IP ACL entry for this location. Except, its not the correct entry. And no matter what IP ACL entry I set my location to, running configctl again does not change what gets put into the nginx config file.

**Comment by Oxima69** [comment] 2020-01-05 16:43
Just tested again

Apparently, it looks that way now. 

1. If an IP ACL is set in the HTTP server, it is inherited to the location IP ACL... 
even if a different rule is set for the location.

2. If an IP ACL is only set in the location block, it does not appear at all

**Comment by Szeraax** [comment] 2020-01-05 17:29
That's consistent with what I'm seeing. Thanks for tracking that down, @Oxima69 !

**Comment by Szeraax** [comment] 2020-01-05 23:10
Seems like this is the cause: https://github.com/opnsense/plugins/blob/10727e31029e3138573345620b3688b3f29c30ee/www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf#L46

**Comment by Szeraax** [comment] 2020-01-06 02:51
Ok, @fabianfrz . Because I really wanted this functionality, I have done the work to make a new package that I can confirm DOES work:
![image](https://user-images.githubusercontent.com/6242511/71791654-0a9f6c80-2ff3-11ea-82f0-b538ec96bd31.png)

Note: I have NO IDEA how we do code tests because that was not mentioned in the workflow document. Steps take to create a new package and test it:

1. Install OPNSense to a new VM (I use hyper-V on windows 10v1909 pro). Install via SSH due to bug
1. pkg install git
1. git clone https://github.com/opnsense/plugins.git
1. cd plugins/www/nginx
1. nano src/opnsense/service/templates/OPNsense/Nginx/location.conf
1. Make needed change to line 46 (set to location.ip_acl instead of server.ip_acl) and exit
1. make package
1. pkg install work/pkg/os-nginx-devel-1.17.txz
1. Go to GUI, bypass wizard, go to nginx plugin, enable nginx
1. Create 2 IP ACLs (one with a 1.1.1.1 allow called 'serverACL', one with a 2.2.2.2 allow called 'locationACL')
1. Create a new location and apply the IP acl to it
1. Create a new http server and apply the location to the server
1. Click the 'build nginx.conf' gui button
1. Verify that the file at /usr/local/etc/nginx/nginx.conf only contains 1 `# IP ACL` block and that it contains the locationACL with 2.2.2.2
1. Edit the HTTP server and add the siteACL
1. Click the 'build nginx.conf' gui button
1. Verify that the file at /usr/local/etc/nginx/nginx.conf only contains 2 `# IP ACL` blocks and that the server one contains 1.1.1.1 and that the location one still contains 2.2.2.2
1. Success!
![image](https://user-images.githubusercontent.com/6242511/71792092-9239ab00-2ff4-11ea-97c6-db86513ad86e.png)

I hope that this comment will serve as a guide to anyone who wants to make changes to a plugin and test. I will now go submit the PR for this plugin.

**Comment by Szeraax** [comment] 2020-01-06 02:55
PR: https://github.com/opnsense/plugins/pull/1653

How long after this PR gets approved will it take before @Oxima69 will be able to use the updated plugin? Should he build the same himself? Should I post my pkg somewhere and have him download+install (if he wants it)?

**Comment by fabianfrz** [comment] 2020-01-06 06:06
@Szeraax the fastest way is to use the OPNsense patch utility. You can pass your user repository to apply it. Since there was no release over the holidays I think there will be one soon and if that get accepted it will be included.

**Comment by fabianfrz** [comment] 2020-01-06 09:10
merged. Execute the following command to apply the patch:

```
opnsense-patch -c plugins 0b3b0be
```

**Comment by Oxima69** [comment] 2020-01-06 10:15
is now working as expected !

thank you

**Comment by Szeraax** [comment] 2020-01-23 20:58
@Oxima69 Can you close this issue?

**Closed** 2020-01-23 21:30 UTC
Labels: bug, support
