### ISSUE TITLE
HAProxy frontend IPv6

### ISSUE THREAD

**Issue by dragon2611** [opnsense/plugins#581] opened 2018-03-05 10:38 UTC
Can someone confirm the expected format for an IPv6 address in the HAproxy config.

I'd like to get HAproxy listening on the V6 address but it seems to only want to take an IPv4 or a host-name.

I've tried encapsulating the IPv6 address in [] like you would for a web-browser and that doesn't seem to help either.

Ideally the context help needs updating to show an example of the expected format

**Comment by fraenki** [comment] 2018-03-05 16:06
Duplicate of bug #540.

**Closed by fraenki** 2018-03-05 16:06 UTC
Labels: support
