### ISSUE TITLE
shadowsocks for opnsense

### ISSUE THREAD

**Issue by Laven7** [opnsense/plugins#467] opened 2018-01-05 03:53 UTC
Could you add a shadowsocks plugin for opnsense

**Comment by fichtner** [comment] 2018-01-05 06:40
shadowsocks-libev is in packages... though which specific shadowsocks application are you referring to?

**Comment by mimugmail** [comment] 2018-01-05 06:51
Is there really a need for this? Config seems really easy .. if there are one or two more guys interested in this I can build a UI.

**Comment by Laven7** [comment] 2018-01-05 07:04
Many people interested in shadowsocks in China. If we could config  shadowsocks like openwrt, we'll be very thankful for what you do

**Comment by fichtner** [comment] 2018-01-05 07:05
Did you know we also have OpenVPN with XOR patch?

https://tunnelblick.net/cOpenvpn_xorpatch.html

Unless you tell me it's not working anymore for reasons beyond the software itself, that would be good to know too.

**Comment by mimugmail** [comment] 2018-01-05 07:08
Every pkg to make it harder for GFOC is a good one! :D Give me some days ..

**Comment by Laven7** [comment] 2018-01-05 07:23
I have configured shadowsocks-libev in my opnsense, but it seems it doesn't work on my PC.
I've heard of OpenVPN, but many people like Shadowsocks much more than OpenVPN in China.

**Comment by mimugmail** [comment] 2018-01-05 07:57
@Laven7 down the shadowsocks also works without a password? Is this a common setup or is password a must?

**Comment by Laven7** [comment] 2018-01-05 08:07
@mimugmail I have a shadowsocks server in my google vps.

**Comment by mimugmail** [comment] 2018-01-05 08:15
@fichtner which value determines the name of the rc script? I'm using shadawsocks everywhere, but the rc script is called shadowsocks_libev. Will I have to rename everything of is this just one value somewhere?

Besides this the plugin is ready/finished ...

**Comment by mimugmail** [comment] 2018-01-05 08:48
forget it .. stupid question :/

**Comment by fabianfrz** [comment] 2018-01-06 12:42
plugin has been merged - closing this

**Comment by mimugmail** [comment] 2018-01-15 15:20
@Laven7 Were you able to test the plugin? Does it work for you?

**Comment by Laven7** [comment] 2018-01-17 08:09
@mimugmail Sorry, I can't get version 18.1.r2 yet.

**Comment by mimugmail** [comment] 2018-01-17 08:11
When you download RC1 ISO and so a fresh Install you can upgrade to RC2

**Comment by fichtner** [comment] 2018-01-17 08:21
It will also be in 17.7.12 tomorrow.

    # pkg install os-openconnect-devel


Cheers,
Franco

**Comment by mimugmail** [comment] 2018-01-17 08:23
shadowsocks, not openconnect :)

**Comment by fichtner** [comment] 2018-01-17 08:25
whoops, fixed :D

**Comment by Laven7** [comment] 2018-01-17 09:26
I'm trying to download RC1 now, but the network doesn't work well.  When I get the test result, I'll let you know. @mimugmail

**Comment by Laven7** [comment] 2018-01-18 08:21
@mimugmail It doesn't  work for me. I have two shadowsocks server and I have tried them all. My server port is 443, local port is 1080, server encryption is aes-256-cfb. but I can't find server encryption configuration in the plugin. 

The log said "bind: Can't assign requested address"

**Comment by mimugmail** [comment] 2018-01-18 08:28
Because your Admin GUI already use 443?

**Comment by Laven7** [comment] 2018-01-18 08:35
NO, I try to set other server port, but it doesn't work.

**Comment by mimugmail** [comment] 2018-01-18 08:44
Would you mind to give me the details so I can test here?
If yes just drop me the settings at
https://github.com/opnsense/plugins/blob/master/net/shadowsocks/Makefile#L5

**Comment by Laven7** [comment] 2018-01-18 08:59
@mimugmail I have sent an email to you, about my server details.

**Comment by mimugmail** [comment] 2018-01-18 09:50
Ok, we had a misunderstanding here. The current package only offers server mode .. it can only bind to a local address. What you need might be tunnel, correct?

**Comment by Laven7** [comment] 2018-01-18 10:32
correct

**Comment by fichtner** [comment] 2018-01-19 07:26
sure, adapt what we have, maybe making sure the rc.d script name reflects that. I didn't know we had a server instance with openconnect anyway?

**Comment by mimugmail** [comment] 2018-01-19 08:52
OpenConnect? Not in the repo .. ;)

**Comment by fichtner** [comment] 2018-01-19 08:54
man I keep mixing those two up...

**Comment by fabianfrz** [comment] 2018-01-19 15:33
@mimugmail it may be like os-tor, which is a client and a server at the same time.

**Comment by mimugmail** [comment] 2018-01-20 07:05
@fabianfrz the problem is the rc script is only for ss-server, there's also ss-tunnel and ss-local.
@Laven7 just to be sure .. you don't need ss-tunnel for static port tunneling? I don't want to make it too complicated :)

**Comment by Laven7** [comment] 2018-01-22 02:10
sure

**Comment by mimugmail** [comment] 2018-02-09 05:45
@Laven7 when you have 0.1 still installed and update to 18.1.2 you'll receive 0.2 which now has a "General" service to deploy a server and "Local" for just ss-local client connecting to an external server. 
Hopefully it works for you now :) Please test it when you find the time ..

**Comment by mimugmail** [comment] 2018-03-01 08:31
@Laven7 ? :)

**Comment by mimugmail** [comment] 2018-03-22 17:02
@lattera my friend of privacy .. you like to test with me the shadow socks plugin? I'd need some external system hosting a shadow server where my client can connect to.

As you drive a tor relay perhaps you'd also try shadow for our chinese OPN users?

**Comment by lattera** [comment] 2018-03-22 17:12
I'd be happy to. Can you give me a test plan?

**Comment by lattera** [comment] 2018-03-22 18:04
Cool. I'll set up a separate OPNsense box and install this behind my primary box and do port forwarding. I prefer to leave my primary box in pristine condition. I'll do that this weekend.

**Comment by Laven7** [comment] 2018-03-23 02:18
@mimugmail 
I'm so sorry,  I'm too busy to check my git message last month. I'll give you my test details ASAP. And I'll send my shadowsocks server info to you. You also can use it to test.

**Comment by Laven7** [comment] 2018-03-23 02:25
@mimugmail 
How can I get your email, I forgot it.

**Comment by mimugmail** [comment] 2018-03-23 05:28
https://github.com/opnsense/plugins/blob/master/net/shadowsocks/Makefile#L5

**Comment by mimugmail** [comment] 2018-03-23 07:19
@Laven7 It's working, great! :)
@lattera If you still interested in testing, I'm on it .
@fichtner You can merge the current master code base to stable!

Thanks to everyone ...

**Comment by fichtner** [comment] 2018-03-23 07:33
> You can merge the current master code base to stable!

That's already the case. Or do you mean you want to release 1.0 ?

**Closed** 2018-10-04 07:54 UTC
Labels: enhancement

**Comment by samirmh-dev** [comment] 2020-10-30 12:44
any support for v2ray plugin?

**Comment by mimugmail** [comment] 2020-10-30 13:54
There is a pkg but no plugin. So you can install and configure via CLI

**Comment by samirmh-dev** [comment] 2020-10-30 15:56
> There is a pkg but no plugin. So you can install and configure via CLI

thank you for fast reply 🚀
