### ISSUE TITLE
Renewal of Let's Encrypt Wildcard Cert fails

### ISSUE THREAD

**Issue by thecmdradama** [opnsense/plugins#1820] opened 2020-05-05 13:30 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
When attempting to renew a wildcard Let's Encrypt cert via DNS-01 with Cloudflare, it will return with the Acme status of validation failed.

**To Reproduce**
1. go to Let's Encrypt > Validation Methods
2. Add a new validation method  with the challenge type DNS-01, DNS service of CloudFlare.com API and add either the global API Key or restricted token and save.
3. Go to Let's Encrypt > Certificates and add a new certificate e.g. domain.com and an alias of *.domain.com. Choose the LE account and Validation method and save. 
4. Issue the cert.

**Expected behavior**
Upon refresh of the page I would expect to see that the Acme status is ok and the issue/renewal time to show when the cert had been issued. 

**Screenshots**
![Annotation 2020-05-05 214323](https://user-images.githubusercontent.com/44428944/81074266-5ae3f800-8f1b-11ea-9174-e793d4594754.png)

**Relevant log files**
[log.txt](https://github.com/opnsense/plugins/files/4581142/log.txt)

**Additional context**
I was able to do a work around by running the following as root, manually adding the txt keys, running the below again then importing the .cer and .key into the Web GUI certs

acme.sh --renew -d domain.com -d *.domain.com --dns dns_cf --home /var/etc/acme-client/home

I did also update acme.sh.
acme.sh version:
https://github.com/Neilpang/acme.sh
v2.8.5

This issue is also discussed here https://forum.opnsense.org/index.php?topic=17067.0

**Environment**
OPNsense 20.1.6 (amd64, OpenSSL).
CPU: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz 
AWS Lightsail instance

**Comment by thecmdradama** [comment] 2020-05-05 13:31
submitted while starting to create issue....

**Comment by thecmdradama** [comment] 2020-05-05 14:03
Corrected original comment and reopened

**Comment by fraenki** [comment] 2020-05-05 14:32
Duplicate of #1817

**Closed by fraenki** 2020-05-05 14:32 UTC
