### ISSUE TITLE
Caddy Reverse-Proxy apply config changes only after firewall restart

### ISSUE THREAD

**Issue by phillipunzen** [opnsense/plugins#3929] opened 2024-04-21 14:55 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ X] The title contains the plugin to which this issue belongs

**Describe the bug**
If you configure Caddy as a reverse proxy, the changes to the config will not be applied via the "Apply changes" button. To do this, the "takeover" takes at least 3 minutes

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
I have configured Caddy as a reverse proxy on my OPNsense. I use my own Let's Encrypt SAN certificate which contains my 7 domains. Unfortunately, I have to restart my entire firewall after every configuration change. When I click on the button with "Apply changes" it takes 3 minutes for the "loading icon" to disappear and then I get a blank page when I open the web pages. After disabling the services and restarting the firewall, I was able to connect.

**Expected behavior**
You don't want the "Apply Changes" button to load that long + changes should really be applied.

**Environment**
Software version used and hardware type if relevant.
Caddy: 1.5.4
OPNsense: 24.1.6

CPU: Intel Core i7 6700
RAM: 8GB
HD: SSD 100GB

**Comment by Monviech** [comment] 2024-04-21 15:19
Could you tell me what happens if you do this command in the shell?

```configctl caddy reload```

**Comment by phillipunzen** [comment] 2024-04-21 19:17
Yes, the command's answer is "OK". 

Log from Caddy:
```
# DO NOT EDIT THIS FILE -- OPNsense auto-generated file


# Global Options
{
        log {
                output net unixgram//var/caddy/var/run/log {
                }
                format json {
                        time_format rfc3339
                }
        }

        servers {
                log_credentials
        }

        email admin@phillipunzen.de
        import /usr/local/etc/caddy/caddy.d/*.global
}

# Reverse Proxy Configuration


# Reverse Proxy Domain: "50a9f8d6-5a66-492b-a311-993a4e74d176"
*.phillipunzen.de {
        log {
                output file /var/log/caddy/access/50a9f8d6-5a66-492b-a311-993a4e74d176.log {
                        roll_keep_for 10d
                }
        }
        tls /var/db/caddy/data/caddy/certificates/temp/660c6eaadca91.pem /var/db/caddy/data/caddy/certificates/temp/660c6eaadca91.key

        @442f8653-7138-4bae-90ba-c18a3b18a434 {
                host nas.phillipunzen.de
        }
        handle @442f8653-7138-4bae-90ba-c18a3b18a434 {
                handle {
                        reverse_proxy 192.168.10.4:5001 {
                                transport http {
                                        tls_insecure_skip_verify
                                }
                        }
                }

                abort
        }
        @1f7dfbdc-c199-454d-a0c9-e7fe76c22527 {
                host autodiscover.phillipunzen.de
        }
        handle @1f7dfbdc-c199-454d-a0c9-e7fe76c22527 {
                handle {
                        reverse_proxy 10.10.1.10:443 {
                                transport http_ntlm {
                                        tls_insecure_skip_verify
                                }
                        }
                }

                abort
        }
        @778fc421-3402-45d6-8d75-cead983db629 {
                host outlook.phillipunzen.de
        }
        handle @778fc421-3402-45d6-8d75-cead983db629 {
                handle {
                        reverse_proxy 10.10.1.10:443 {
                                transport http_ntlm {
                                        tls
                                        tls_trusted_ca_certs /var/db/caddy/data/caddy/certificates/temp/660c3ba6b7c2a.pem
                                        tls_server_name outlook.phillipunzen.de
                                }
                        }
                }

                abort
        }
        @d60e7ce9-4f27-457e-b6d0-8800d7913773 {
                host bitwarden.phillipunzen.de
        }
        handle @d60e7ce9-4f27-457e-b6d0-8800d7913773 {
                handle {
                        reverse_proxy 10.10.1.11:50002 {
                        }
                }

                abort
        }
        @c85fbc40-e6bf-40f6-a28e-1acb9a54821a {
                host graph.phillipunzen.de
        }
        handle @c85fbc40-e6bf-40f6-a28e-1acb9a54821a {
                handle {
                        reverse_proxy 10.10.1.11:50001 {
                        }
                }

                abort
        }
        @e34c262a-7256-496f-bf47-46f66c2b4285 {
                host mailproxy.phillipunzen.de
        }
        handle @e34c262a-7256-496f-bf47-46f66c2b4285 {
                handle / {
                        reverse_proxy 10.10.1.6:8006 {
                                transport http {
                                        tls_insecure_skip_verify
                                }
                        }
                }

                abort
        }

        abort
}
# Reverse Proxy Domain: "ab2f4b1b-b3de-4dbb-b86c-32579ac56c96"
*.marlenenitsch.de {
        log {
                output file /var/log/caddy/access/ab2f4b1b-b3de-4dbb-b86c-32579ac56c96.log {
                        roll_keep_for 10d
                }
        }
        tls /var/db/caddy/data/caddy/certificates/temp/660c6eaadca91.pem /var/db/caddy/data/caddy/certificates/temp/660c6eaadca91.key

        @58b0244b-5b1c-44ef-8499-b7d6bfa5f8ac {
                host outlook.marlenenitsch.de
        }
        handle @58b0244b-5b1c-44ef-8499-b7d6bfa5f8ac {
                handle {
                        reverse_proxy 10.10.1.10:443 {
                                transport http_ntlm {
                                        tls
                                        tls_trusted_ca_certs /var/db/caddy/data/caddy/certificates/temp/660c3ba6b7c2a.pem
                                        tls_server_name outlook.marlenenitsch.de
                                }
                        }
                }

                abort
        }

        abort
}
# Reverse Proxy Domain: "4f82f387-96c2-41e4-8b91-5ca31c788c93"
*.petersen-nf.com {
        log {
                output file /var/log/caddy/access/4f82f387-96c2-41e4-8b91-5ca31c788c93.log {
                        roll_keep_for 10d
                }
        }
        tls /var/db/caddy/data/caddy/certificates/temp/660c6eaadca91.pem /var/db/caddy/data/caddy/certificates/temp/660c6eaadca91.key

        @5ee26eb3-af69-44f1-9730-19bae0217e9c {
                host autodiscover.petersen-nf.com
        }
        handle @5ee26eb3-af69-44f1-9730-19bae0217e9c {
                handle {
                        reverse_proxy 10.10.1.10:443 {
                                transport http_ntlm {
                                        tls
                                        tls_trusted_ca_certs /var/db/caddy/data/caddy/certificates/temp/660c3ba6b7c2a.pem
                                        tls_server_name outlook.petersen-nf.com
                                }
                        }
                }

                abort
        }
        @7cf52f27-5e6c-464c-b967-c1aa95ff102e {
                host outlook.petersen-nf.com
        }
        handle @7cf52f27-5e6c-464c-b967-c1aa95ff102e {
                handle {
                        reverse_proxy 10.10.1.10:443 {
                                transport http_ntlm {
                                        tls
                                        tls_trusted_ca_certs /var/db/caddy/data/caddy/certificates/temp/660c3ba6b7c2a.pem
                                        tls_server_name outlook.petersen-nf.com
                                }
                        }
                }

                abort
        }
        @f188404b-030a-4de5-adff-d13cdbecb989 {
                host bitwarden.petersen-nf.com
        }
        handle @f188404b-030a-4de5-adff-d13cdbecb989 {
                handle {
                        reverse_proxy 10.10.1.11:50002 {
                        }
                }

                abort
        }

        abort
}
# Reverse Proxy Domain: "c9600d62-f914-42ee-8abc-3e2b03364674"
*.pc-wiki.de {
        log {
                output file /var/log/caddy/access/c9600d62-f914-42ee-8abc-3e2b03364674.log {
                        roll_keep_for 10d
                }
        }
        tls /var/db/caddy/data/caddy/certificates/temp/660c6eaadca91.pem /var/db/caddy/data/caddy/certificates/temp/660c6eaadca91.key

        @7c80c3e9-338a-4b0d-8425-e66faccee797 {
                host www.pc-wiki.de
        }
        handle @7c80c3e9-338a-4b0d-8425-e66faccee797 {
                handle {
                        reverse_proxy 10.10.1.11:65002 {
                        }
                }

                abort
        }
        @81c60c33-7701-4b6b-9714-583fa5ed6772 {
                host pc-wiki.de
        }
        handle @81c60c33-7701-4b6b-9714-583fa5ed6772 {
                handle {
                        reverse_proxy 10.10.1.11:65002 {
                        }
                }

                abort
        }

        abort
}
# Reverse Proxy Domain: "55e55083-863c-44f0-ab2a-dbd7178528a4"
*.phlene.de {
        log {
                output file /var/log/caddy/access/55e55083-863c-44f0-ab2a-dbd7178528a4.log {
                        roll_keep_for 10d
                }
        }
        tls /var/db/caddy/data/caddy/certificates/temp/660c6eaadca91.pem /var/db/caddy/data/caddy/certificates/temp/660c6eaadca91.key

        abort
}

import /usr/local/etc/caddy/caddy.d/*.conf
```

I have 2 certificates on the OPNsense.
1. Self-Signed Web GUI TLS Certificate (Never Used)
2. SAN-Certificate (From ACME-Client) => It include all Domains ex. _domain.de_ and _*.domain.de_

I hope this information helps!

**Comment by phillipunzen** [comment] 2024-04-21 19:20
Oh, I have an idea for a future update. Would it be possible to create a handler for several subdomains? For example, you have to create a handler for each individual subdomain, which is a bit confusing in the long run :)

**Comment by Monviech** [comment] 2024-04-21 19:29
Thanks for the information. I'll see what I can do. Tell me, if you change the config in the GUI, for example deactivating a domain (without pressing apply!), and then use the CLI to invoke the reload, has the configuration changed and caddy is successfully running with this altered configuration?

Regarding your request, I don't think I can implement that without a complete rewrite of the template logic and a major overhaul of how the GUI works right now. Using the search of the bootgrid makes it a bit more user friendly for big configurations. The scope I wrote this plugin for were small home users though who have a few domains. Big configurations always become challenging in these kind of grid UIs.

**Comment by phillipunzen** [comment] 2024-04-22 14:35
Yes, Caddy is running. But if i open the website, i get a blank page. I must restart the Firewal after config change... 

It's a pity, because this would be a feature that I think could be of great use in other homelabs as well.

Okay, i can select more subdomains with the columns?

**Comment by phillipunzen** [comment] 2024-04-22 14:47
Or optionally ERR_HTTP2_Protocol_Error

**Comment by Monviech** [comment] 2024-04-22 17:48
Lets focus on the issue. I can't do that feature request since the way the template works is pretty much finished and works great for all kinds of configurations.

I have a setup where I can reproduce the issue of "service caddy stop" taking around 10 minutes or longer, while using custom wildcard certificates. I'm in contact upstream and come back to this once I know more.

**Comment by Monviech** [comment] 2024-04-22 19:18
@phillipunzen Can you try this out? It solved it for me.

```cd /usr/local/etc/caddy/caddy.d/```
```vi graceperiod.global```

Inside vi, press ```i``` to get into edit mode.
Put this line into the file:
```grace_period 5s```
then press ```ESC``` and input ```:wq!``` and press ```ENTER```

Afterwards Apply in the GUI, it should reload now after 5 seconds. If not, try to restart your firewall one time, and then try it a few times with the apply.

The problem should be, that there is an open connection (probably to the exchange server you are reverse proxying) that won't get dropped with the default settings of Caddy. Caddy keeps all connections open, and if there is a stream, that might be forever.

https://caddyserver.com/docs/caddyfile/options#grace-period

**Comment by phillipunzen** [comment] 2024-04-23 11:23
I just did this on myself. I had to restart the firewall once, but the configuration seems to be reloading now. The change will be rolled out with the next update, right?

Does this also solve the “Blank Page Problem”?

**Comment by Monviech** [comment] 2024-04-23 11:27
Yeah this fix will be included in the next update. Just don't forget to remove the custom file when it happens, because otherwise it will say something like "duplicate parameter in config".

I don't know if it fixes the blank page problem. Please keep me updated if you encounter it again.

**Closed** 2024-04-26 07:42 UTC

**Comment by phillipunzen** [comment] 2024-04-28 14:56
Update: the issue with the "endless" reload is back... The file exist in the filesystem. When come's the update for the plugin?

**Comment by Monviech** [comment] 2024-04-28 15:18
Probably comes with 24.1.7.

You can delete the file though and already patch the plugin if you want to. Execute these one after another:

```
opnsense-patch -c plugins 3a559f91f2d0a094531eda8e3ec6e1814ba1a7ac
opnsense-patch -c plugins 8ec93bd7c972a062a28ffcfe2026233bee210d90
opnsense-patch -c plugins 2ec0eef44012151aa88b02c859803694eca09387
opnsense-patch -c plugins 3f4beb965624901689f93c0ab6f90d526a9db3dd
```
