### ISSUE TITLE
[node_exporter] error spam

### ISSUE THREAD

**Issue by oasisck** [opnsense/plugins#1361] opened 2019-06-07 10:17 UTC
Hi, got those messages every 20s even when I disable memory stats in plugin
```
node_exporter[99853]: time="2019-06-07T11:41:25+02:00" level=error msg="ERROR: meminfo collector failed after 0.000085s: couldn't get memory: no such file or directory" source="collector.go:132"
```
It seems to be fine about memory on port 9100
```
[...]
# HELP node_memory_active_bytes Recently used by userland
# TYPE node_memory_active_bytes gauge
node_memory_active_bytes 3.9841792e+07
# HELP node_memory_buffer_bytes Disk IO Cache entries for non ZFS filesystems, only usable by kernel
# TYPE node_memory_buffer_bytes gauge
node_memory_buffer_bytes 3.73116928e+08
# HELP node_memory_cache_bytes Almost free, backed by swap or files, available for re-allocation
# TYPE node_memory_cache_bytes gauge
node_memory_cache_bytes 0
# HELP node_memory_free_bytes Unallocated, available for allocation
# TYPE node_memory_free_bytes gauge
node_memory_free_bytes 6.73431552e+08
# HELP node_memory_inactive_bytes Not recently used by userland
# TYPE node_memory_inactive_bytes gauge
node_memory_inactive_bytes 2.602336256e+09
# HELP node_memory_size_bytes Total physical memory size
# TYPE node_memory_size_bytes gauge
node_memory_size_bytes 4.047929344e+09
# HELP node_memory_wired_bytes Locked in memory by kernel, mlock, etc
# TYPE node_memory_wired_bytes gauge
node_memory_wired_bytes 7.3252864e+08
[...]
```
Got the latest Prometheus version on server side
```
prometheus --version
prometheus, version 1.5.2+ds (branch: debian/sid, revision: 1.5.2+ds-2+b3)
```
Thanks for your fabulous work 👍

**Comment by StopTrain** [comment] 2019-06-15 03:50
I'm seeing the same meminfo spam as well.  I'll try disabling the collector itself and see if it goes away.

**Comment by StopTrain** [comment] 2019-06-15 03:54
I do see the same issue.  Even with disabling it in the GUI and restarting/stopping then starting, it still shows the meminfo is being loaded and still trying to run

**Comment by kdomanski** [comment] 2019-06-18 08:44
That's a bug in node_exporter itself https://github.com/prometheus/node_exporter/pull/1345 and it is fixed in version 0.18.1

**Comment by mimugmail** [comment] 2019-06-28 13:29
This is not my plugin :)

**Comment by fabianfrz** [comment] 2019-06-29 16:57
@mimugmail sorry, I thought it was yours. I am loosing the overview because you made so many ;)

**Comment by kdomanski** [comment] 2019-07-06 10:52
The node-exporter 0.18.1 update has arrived on OPNSense and at least for me the issue is gone.

**Comment by fichtner** [comment] 2019-07-06 22:26
@kdomanski thanks, closing

**Closed by fichtner** 2019-07-06 22:26 UTC
Labels: upstream
