### ISSUE TITLE
 [Feature Request] Manage Proxy Trust through Webinterface

### ISSUE THREAD

**Issue by AndyX90** [opnsense/plugins#838] opened 2018-09-11 09:14 UTC
Hey guys,
it would be great to have an option via the Webinterface to edit the squid certificate database.
Something like this:
![grafik](https://user-images.githubusercontent.com/10565317/45350311-c1ccd480-b5b3-11e8-9ecd-c74f2f664906.png)

**Comment by fabianfrz** [comment] 2018-09-12 17:34
first of all, it belongs to opnsense/core and it is also a duplicate of opnsense/core#1460

@fichtner what do you think?

**Comment by fichtner** [comment] 2018-09-12 18:28
yep

@fabianfrz we usually tag "support" for all non-functional tickets

**Comment by fabianfrz** [comment] 2018-09-12 18:47
ok, but duplicate is also true in this case. close?

**Comment by fichtner** [comment] 2018-09-12 18:54
I deleted the labels we don't want... you can close it if you copy @AndyX90 's picture to your OP?

**Comment by fabianfrz** [comment] 2018-09-12 19:15
I won't copy but cross reference (link the image into the other ticket).

**Closed by fabianfrz** 2018-09-12 19:15 UTC
Labels: support
