### ISSUE TITLE
Issue with HAproxy after factory reset

### ISSUE THREAD

**Issue by errolsancaktar** [opnsense/plugins#2621] opened 2021-10-30 02:48 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
reinstalling from scratch and restoring from config backup haproxy will no longer work properly.  i'm not seeing any of the frontends/backends etc in the gui and when i look in /usr/local/etc/ there is no haproxy.conf or haproxy.conf.staging.  i tried copying a backup of that file back into the right locations but that doesnt work either because its missing some of the certs that normally live in /tmp/haproxy/ssl.  i removed the haproxy.conf and .staging file and tried reinstalling the plugin, adding a very basic frontend to the gui but it does not seem to update or create the .staging or .conf files.  i touched both of the files so that they were there, empty and have root:wheel 644 perms but it does not put anything into the files when i test and apply.  trying to start the service both through the gui and through temrinal did not work.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. reinstall opnsense
2. restore from backup
3. try to get haproxy running which fails

**Expected behavior**
i would expect that removing all of the configurations and reinstalling the plugin would give me a fresh start for haproxy.

**Screenshots**
![Screenshot from 2021-10-29 20-44
![Screenshot from 2021-10-29 20-45-10](https://user-images.githubusercontent.com/60162646/139517677-65bb9584-9a53-4b23-8eaa-07280a08299f.png)
-21](ht
![Screenshot from 2021-10-29 20-44-45](https://user-images.githubusercontent.com/60162646/139517675-71951392-c240-4082-a100-56199ef89303.png)
tps://user-images.githubusercontent.com/60162646/139517671-b4d67928-f7df-4181-8824-43e00d608be4.png)
If applicable, information from log files supporting your c
![Screenshot from 2021-10-29 20-44-29](https://user-images.githubusercontent.com/60162646/139517674-270aab91-0df7-4520-92bb-7451f9b0001a.png)

**Relevant log files**
i'm not sure where the log files would be

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 21.7.4-amd64FreeBSD

Intel(R) Celeron(R) CPU J1900 @ 1.99GHz (4 cores)
--

<br class="Apple-interchange-newline">

**Comment by kulikov-a** [comment] 2021-10-30 09:53
related imho
https://github.com/opnsense/plugins/issues/2616

**Comment by fraenki** [comment] 2021-10-31 20:31
Indeed, looks like a duplicate of #2616.

**Closed by fraenki** 2021-10-31 20:31 UTC
