### ISSUE TITLE
Acme-Client Causes OPNSense 18.1 crash report.

### ISSUE THREAD

**Issue by BoardWatcher** [opnsense/plugins#539] opened 2018-02-01 10:19 UTC
I just upgraded to 18.1 from 17.7.12_1 as suggested by Frank.  I am experiencing issues with the Let's Encrypt configuration which causes an error on the OPNsense 18.1_1-amd64 dashboard.  I'm attaching a file which has the error messages and the log files. 

Again, please advise.
Thank you
[LetsEncrypt_Error.txt](https://github.com/opnsense/plugins/files/1685067/LetsEncrypt_Error.txt)

**Comment by fraenki** [comment] 2018-02-01 14:13
@BoardWatcher: Thanks for your report!
If I'm not mistaken the error that you're seing in the OPNsense dashboard is the following:

`[01-Feb-2018 22:58:52 Pacific/Auckland] PHP Warning:  cert_action_validator(): Node no longer exists in /usr/local/opnsense/scripts/OPNsense/AcmeClient/certhelper.php on line 122`

This is a known issue that we'll try to address in one of the next releases.
I'm closing this issue as a duplicate of #333. If a fix is available it will be posted in issue #333.

**Closed by fraenki** 2018-02-01 14:13 UTC
Labels: bug
