### ISSUE TITLE
SMART tools: NVMe ssd can't not detect.

### ISSUE THREAD

**Issue by chienchoupan** [opnsense/plugins#1384] opened 2019-07-03 07:51 UTC
I have the same issue. My disk is samsung 970 evo plus NVMe M.2 250G, when I install smart tools, it also shows that no SMART device is found.

 I guess the problem is the device ID different. The SATA type will be ada0, but NVMe type will be nvme0, so I used command "  /usr/local/sbin/smartctl -a /dev/nvme0" , it will show smart information normally. So I hope the web GUI can fixd this issue in the future thanks.

**Comment by fichtner** [comment] 2019-07-03 07:57
@evbevz @kekek2 @Sergey-Kirpa anyone wanna take this?

**Comment by Nimloth** [comment] 2019-07-19 18:37
Just a few comments:

the block device will be for instance /dev/nsd0, the partition /dev/nsd0p3, etc.
the device supports the ioctl required by diskinfo, but **not smart**
the nvme device will be for instance /dev/nvme0
this **does not** support the ioctl required by diskinfo, but it does do smart.

I do not know how you identify which nvme device maps to which nvd. Especially since nvme devices could be using more than one namespace (/dev/nvme0ns1, /dev/nvme0ns2, etc.)

At any rate, I would suggest using smart for fetching the ident string (The serial number, really).
You can do something like this in opnsense/scripts/OPNsense/Smart/detailed_list.sh:

```
ident=`/usr/local/sbin/smartctl -a /dev/$dev | grep 'Serial Number' | awk -F ': *' '{print $2}'`;
```

**Comment by fichtner** [comment] 2019-08-23 08:20
@chienchoupan @Nimloth @payback007 would you mind testing how 2.1 (19.7.3) works for NVMe?

**Comment by Nimloth** [comment] 2019-08-23 10:17
> @chienchoupan @Nimloth @payback007 would you mind testing how 2.1 (19.7.3) works for NVMe?

The Dashboard widget now works. (with a Samsung SSD 970 EVO Plus NVMe drive)

However, the SMART plugin's page (where you can select a device and start a self-test, etc.) still does not list my drive.

**Comment by fichtner** [comment] 2019-08-23 10:36
@Nimloth maybe you're missing https://github.com/opnsense/plugins/commit/1a3517ec8a ... a few more commits made it to master branch

**Comment by fichtner** [comment] 2019-08-23 10:36
(specifically https://github.com/opnsense/plugins/commit/1a3517ec8a#diff-23dffcf9cfb3fefb410ad172ef99ff4fR2)

**Comment by Nimloth** [comment] 2019-08-23 11:04
Ah! I had looked at a different revision, apparently. (the changes Sergey-Kirpa proposed).
Anyway, with https://github.com/opnsense/plugins/commit/1a3517ec8a:
In the Widget, it detects the device nvd0 and gets a string for Ident, but the SMART Status is just a red box,
The output of the script (if run on console) is:
```
[{"device":"nvd0","ident":"S4EUNG0M211406P","state":{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      0
    ],
    "svn_revision": "4883",
    "platform_info": "FreeBSD 11.2-RELEASE-p12-HBSD amd64",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-jH",
      "/dev/nvd0"
    ],
    "messages": [
      {
        "string": "/dev/nvd0: To monitor NVMe disks use /dev/nvme* device names",
        "severity": "error"
      }
    ],
    "exit_status": 1
  }
}}]
```

The smart plugin page does not list the device at all. Probably for the same reason:
```
sysctl -n kern.disks
```
returns nvd0, but smartctl apparently needs to be run against /dev/nvme

**Comment by fichtner** [comment] 2019-08-23 11:28
Wow, it's so clever to complain about the wrong name but not as clever to fix it automatically. :D

Try 790ab76 on top then....

**Comment by fichtner** [comment] 2019-08-23 11:29
PS: maybe ident is broken now, I'm not sure

**Comment by Nimloth** [comment] 2019-08-23 11:35
Yes, ident is now broken.
If ident is supposed to be the serial number (which seems to be the case), then you could get that using smart also:
ident=`/usr/local/sbin/smartctl -a /dev/$dev | grep 'Serial Number' | awk -F ': *' '{print $2}'`;
However, I am not sure how reproducible / reliable that is.

**Comment by Nimloth** [comment] 2019-08-23 11:44
Oh and, diskinfo fails too:

```
/usr/sbin/diskinfo /dev/nvme0
diskinfo: /dev/nvme0: ioctl(DIOCGMEDIASIZE) failed, probably not a disk.
```
Is it necessary to test if a device is a disk like that? I mean if it is not, smartctl should report an error, right?

I can cobble together a version of these that does the job on my system, but I'd need someone to verify if it still works with other device types.

**Comment by fichtner** [comment] 2019-08-23 11:57
Try latest master... the diskinfo is only for serial now, ideally diskinfo -s is preferable to some awk/pipe/grep magic so we can try like in 6ee1662.

**Comment by Nimloth** [comment] 2019-08-23 12:24
The script runs without problems now.

output of the script:
```
/usr/local/opnsense/scripts/OPNsense/Smart/detailed_list.sh
[{"device":"nvme0","ident":"S4EUNG0M211406P","state":{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      0
    ],
    "svn_revision": "4883",
    "platform_info": "FreeBSD 11.2-RELEASE-p12-HBSD amd64",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-jH",
      "/dev/nvme0"
    ],
    "exit_status": 0
  },
  "device": {
    "name": "/dev/nvme0",
    "info_name": "/dev/nvme0",
    "type": "nvme",
    "protocol": "NVMe"
  },
  "smart_status": {
    "passed": true,
    "nvme": {
      "value": 0
    }
  }
}}]
```

The widget still displays a red box instead of the status, which I don't get as
```
if ($dev->state->smart_status->passed) {
            $dev_state_translated = gettext('OK');
            $color = 'success';
```
should be true and thus the result in a nice green OK.
Am I missing something in the way I test the updated code?
I basically uninstalled the smart plugin,
git cloned opnsense/plugins and in ~/plugins/sysutils/smart ran `make install`

**Comment by fichtner** [comment] 2019-08-23 12:30
# make upgrade

It will run a correct sequence for e.g. restarting configd with the new parameter for listing.

**Comment by fichtner** [comment] 2019-08-23 12:31
Dashboard widget doesn't refresh I think, so it needs a reload of the page.

**Comment by Nimloth** [comment] 2019-08-23 12:37
same result.

does anything depend on changes in opnsense itself?

**Comment by fichtner** [comment] 2019-08-23 12:56
Would you mind attaching a screenshot?

**Comment by Nimloth** [comment] 2019-08-23 12:59
Not necessary. Since there was nothing to suggest that the code was wrong, I rebooted and it works now. Is suppose this was some sort of caching issue?
Also the plugin page now works.

**Comment by fichtner** [comment] 2019-08-23 13:00
Not sure, but glad to hear. Shall we close this then and ship all of it in 19.7.3? :)

**Comment by Nimloth** [comment] 2019-08-23 13:01
That works for me! :-)

**Comment by fichtner** [comment] 2019-08-23 13:02
Ok, great. Thanks a lot for your help ❤️

**Closed by fichtner** 2019-08-23 13:02 UTC
Labels: feature
