### ISSUE TITLE
DNSCrypt-Proxy plugin gets confused when Unbound is running on a different interface

### ISSUE THREAD

**Issue by jaydeethree** [opnsense/plugins#3452] opened 2023-05-31 17:34 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**

I have two different networks - 192.168.1.0/24 and 10.10.10.0/24. I want to use different DNS resolvers for each network, so I set up Unbound to listen on 192.168.1.1:53 and confirmed with `netstat` that it's only listening on that interface. However when I try to set up DNSCrypt-Proxy to listen on 10.10.10.1:53, I get the error "Unbound DNS is currently using one of these ports." This is false though - Unbound **is** listening on port 53, but it's listening on a different interface - nothing is listening on 10.10.10.1:53 and `netstat` confirms this.

If I stop Unbound then DNSCrypt-Proxy will allow me to set this up. After doing that I can restart Unbound and everything works correctly. So it seems like there's some sort of issue where the UI won't allow this to be configured even though it's a valid configuration.

**To Reproduce**
1. Have two different network interfaces.
2. Configure Unbound on one interface, listening on port 53.
3. Attempt to configure DNSCrypt-Proxy on the other interface, listening on port 53.
4. Receive error

**Expected behavior**
It should be possible to set this up through the UI without receiving an error.

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
OPNsense 23.1.9-amd64
os-dnscrypt-proxy version 1.13_1
Network Intel I340-T2

**Comment by jaydeethree** [comment] 2023-05-31 20:13
I attached screenshots of everything that seems relevant - let me know if you need any other info. Here's `netstat` from the same time, showing that nothing is listening on 10.10.10.1:53:

```
root@OPNsense:~ # netstat -a -n | grep 53 | sort | uniq
tcp4       0      0 127.0.0.1.53           *.*                    LISTEN
tcp4       0      0 192.168.1.1.53         *.*                    LISTEN
tcp4       0      0 192.168.3.1.53         *.*                    LISTEN
udp4       0      0 127.0.0.1.53           *.*
udp4       0      0 192.168.1.1.53         *.*
udp4       0      0 192.168.3.1.53         *.*
```
![interfaces](https://github.com/opnsense/plugins/assets/34945248/d2b8c10c-0ec4-4c00-be4a-803737a52a7e)
![dnscrypt2](https://github.com/opnsense/plugins/assets/34945248/4c597754-dcdd-4809-9b33-8dafb1b2ca0c)
![dnscrypt1](https://github.com/opnsense/plugins/assets/34945248/bfb889fe-5057-43b4-8140-df4038452240)
![unbound](https://github.com/opnsense/plugins/assets/34945248/9e54de5b-afc6-4f21-aee3-2bf06270851c)


Thanks!

**Comment by fichtner** [comment] 2023-05-31 20:19
Ok, I checked the code and it’s indeed the intended behaviour closing more gaps between core DNS services and plugin DNS services. In core you can’t run Dnsmasq over same port as Unbound and vice versa. The idea and implementation is that a DNS service listens to any address by default. Although restrictions apply it’s more of an advanced setting that can bring joy and tears to your config. To avoid mute problems each DNS service needs to handle its own ports and if you need a port redirect use port forwarding to achieve that explicitly.


Cheers,
Franco

**Closed** 2023-11-27 17:06 UTC
