### ISSUE TITLE
ZeroTier Static IP not preserved upon reboot.

### ISSUE THREAD

**Issue by theonemcdonald** [opnsense/plugins#1616] opened 2019-12-09 21:46 UTC
**Describe the bug**
Running latest 19.7.7 with ZeroTier. I've configured a static IPv4 address on the ZT interface. This works fine until a reboot. After a reboot I have to go into the ZT interface and "save" the settings to bring back the static IPv4 address.

Both the Dashboard and console show a blank IP configuration until I re-"save" the interface.

OPNsense 19.7.7-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.0.2t 10 Sep 2019

**Comment by ruworuro** [comment] 2020-03-28 16:26
the problem is that the opnsense seems to try to configure the ip in the interface before it is available.

One patch is to create a cron job so that after a restart it loads the interface configuration. In my case I have it as part of a bridge and the cron task in /etc/cron.d/zerotier with the content "@reboot root ifconfig br0 addm zt.... up"

**Comment by mimugmail** [comment] 2020-03-28 16:35
You have to tick Lock Interface in Interface config

**Comment by ruworuro** [comment] 2020-04-23 10:17
I have activated the Lock Interface box. After a restart the interface does not pick up the IP.

This OPNSense does not have the patch I mentioned for the bridge. I have added myself to a zerotier network, I have deactivated the interface management by zerotier (zerotier-cli set xxxxx allowManaged=0) and assigned it to a new zerotier interface with a static IP and the Lock Interface checkbox.

**Comment by ruworuro** [comment] 2020-04-23 10:23
Is it possible that the interface management is done before the zerotier network itself is created?

**Comment by AdSchellevis** [comment] 2020-07-05 09:55
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Closed by AdSchellevis** 2020-07-05 09:55 UTC
