### ISSUE TITLE
net/haproxy: service setup/crash

### ISSUE THREAD

**Issue by kisst** [opnsense/plugins#3811] opened 2024-02-08 17:19 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The HAProxy service does not start at boot, and does not restart when crashed.

**To Reproduce**

Enable the service and reboot the device.

**Expected behavior**

When the service is enabled it should auto start, and auto restart if crashed.

**Describe alternatives you considered**

I am currently starting it up every time by hand, I tried to enable/disable the service, no difference. Now I monitor the service from an external host, and restart when needed.

**Environment**

OPNsense 24.1_1-amd64
DEC840

**Comment by fraenki** [comment] 2024-02-19 17:35
> The HAProxy service does not start at boot

Any error message available? If not, a HAProxy config export might help to find the root cause of this issue.

A wild guess: one of your HAProxy "Public Services" is using a WAN IP. If your WAN connection is not setup, then HAProxy fails to start. This may be the case on boot. Simple fix: do not use a WAN IP in HAProxy, but instead use a local IP and add a NAT rule to forward traffic from your WAN IP to your local IP.

> and does not restart when crashed

That's by design. There is no service supervisor in use, hence there is no automatic restart available.

In my personal experience it is _extremely rare_ that the HAProxy service "crashes" (in the sense that it stops due to a software bug). So there should not be a need to automatically restart HAProxy. It would be a good idea to find out what is causing the service to malfunction.

**Comment by kisst** [comment] 2024-02-20 08:12
I have not located related logs yet, but to be honest did not look too deep yet either, nor know right now where should I look for it. I tried few times, and after I had to start it up every time I rebooted, I felt that it's not normal and should be reported, but I do admit I have not spent enough time to debug it myself, I tried to disable/enable again, checked quickly the logs and that's about it, I hope this report will at least be useful for others with similar issue, even if it will not result in a bugfix. All that aside ... 

The WAN interface specifically isn't used however you might be up to something with that guess, as there is one interface which might be blocking startup and that's related to my SD-WAN, so while the NAT workaround might work, knowing how easy this would be with systemd, just setup dependencies, I am having a hard time accepting that it's too hard in BSD, and there for I need apply a workaround rather then a solution, like just have service startup order enforced.

As far as I read the documentation something [like this](https://man.freebsd.org/cgi/man.cgi?query=rcorder%288%29&sektion=) might be a suitable solution.

Although I see how the workaround remove the dependency and make the service more resilient, and I guess if this would be done as part of the config in a background, probably would not even see it as a workaround, but the UX for the NAT-ing just sub-optimal as is.

Related to the frequency of crashes, my experience is different, it happens quite frequently up to the point that I setup a monit rule for it as it was frustrating to deal with.

> There is no service supervisor in use, hence there is no automatic restart available.

This was not just new but shocking to me, I guess I need to dive in and read up on the subject. I kind of expected self healing states.

**Comment by fraenki** [comment] 2024-02-20 10:54
> I have not located related logs yet, but to be honest did not look too deep yet either, nor know right now where should I look for it.

You should see messages on the console during boot that should tell us why HAProxy is unable to start.

> as there is one interface which might be blocking startup and that's related to my SD-WAN

I don't know anything about SD-WAN on OPNsense, so there's not much I can contribute. Having a look at the logs might reveal how and when it is started, which in turn might help to find a solution.

**Comment by kisst** [comment] 2024-02-20 13:33
Not much in the logs.
```
2024-02-19T13:10:39	Notice	kernel	<118>/usr/local/etc/rc.d/haproxy: WARNING: failed to start haproxy	
2024-02-19T13:10:39	Notice	kernel	<118>Starting haproxy.	
2024-02-19T13:10:39	Notice	root	/usr/local/etc/rc.d/haproxy: WARNING: failed to start haproxy
```
However I can see that the ZeroTier starts after HAProxy, so that supports the non-available interface idea, but without having an option to set the `rcorder` I don't see how would I fix that apart from NAT magic, also unsure why there is no more details in the log.
Maybe under the service setting , there could be an advance option for rc order
![image](https://github.com/opnsense/plugins/assets/4265867/4e5a8d6d-16af-4a08-91d3-fa3971b4fb73)


On a separated note, turning off the "introduction pages" makes no impact, no amount of reload / restart applied it.

**Comment by fraenki** [comment] 2024-02-20 13:48
> However I can see that the ZeroTier starts after HAProxy, so that supports the non-available interface idea

Thanks for the confirmation. Let me check how the ZeroTier plugin handles service startup...

**Comment by fraenki** [comment] 2024-02-20 15:45
> Let me check how the ZeroTier plugin handles service startup...

In theory the services should start in the correct order. However, there's a bug or rather an unexpected behaviour that causes the services to start in an incorrect order. I've proposed a fix in https://github.com/opnsense/core/pull/7259.

**Comment by fraenki** [comment] 2024-02-20 17:14
The wrong service start order during system boot can be fixed by applying the following patch:

```
# opnsense-patch edf756e
```

Regarding the crashes: we definitely need more information. Some things to check when it crashes again:
* Most recent HAProxy log entries (either from the GUI or from `/var/log/haproxy/latest.log`)
* Search the system log for entries related to HAProxy
* Is the page `Services: HAProxy: Statistics` still accessible and shows stats data?
* Output of `service haproxy status`
* Output of `ps auxww | grep haproxy`
* Output of `ls -l /var/run/haproxy.*`
* Output of `sockstat -l | grep haproxy` (feel free to redact IP information)

Please collect this information when HAProxy is unavailable for you and before starting/restarting HAProxy.

**Comment by kisst** [comment] 2024-02-21 07:33
Awesome , thanks @fraenki  and I guess fichtner from the merge, I will apply the patch and do a restart to test the changes outside of office hours tonight, if that works will close the issue. 
About the crashes, I will now disable the auto-restart I hacked in via n8n, and will keep an eye on it, to keep things clear I will report that in a separated issue once I have data to show for.

**Comment by kisst** [comment] 2024-02-22 04:08
I can confirm that the patch works, I applied the patch then reboot and haproxy started up fine.

How will the system update handle the presence of the patch ? Will I have to remove it before upgrade ( when the patch made it mainline ) or will it be just handled without removing it ? ( because now I would like to keep it in place for stability )

**Comment by fraenki** [comment] 2024-02-22 12:58
After every OPNsense upgrade you'll have to re-apply the patch for the time being.

There's a chance that this modification has unwanted side-effects, so it'll linger in the development version for some time, but will eventually be release in a stable version in the future. Please watch the OPNsense release notes, they'll contain more information when it's released in a stable version.

**Closed** 2024-02-22 17:49 UTC
Labels: support
