### ISSUE TITLE
ddclient: Porkbun API endpoint changing

### ISSUE THREAD

**Issue by skruje** [opnsense/plugins#4298] opened 2024-10-15 13:21 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Porkbun has announced a change to its API address from https://porkbun.com to https://api.porkbun.com with a deadline of 2024-12-01 00:00:00 UTC. There's already a PR in the upstream: https://github.com/ddclient/ddclient/pull/752, once this is merged, OPNsense should pull in the latest bits from the project to ensure continuity of support for Porkbun.

**Expected behavior**
ddclient should use https://api.porkbun.com to update DDNS records on Porkbun 

**Additional context**
```
CRITICAL UPDATE DETAILS

Type: API Hostname Change

Old Value: porkbun.com

New Value: api.porkbun.com

Deadline: 2024-12-01 00:00:00 UTC
```

**Comment by AdSchellevis** [comment] 2024-10-15 14:20
@skruje can you try the PR and confirm that it currently works? I can merge the code after confirmation

**Comment by AhnHEL** [comment] 2024-11-26 20:59
@AdSchellevis 

The PR at https://github.com/ddclient/ddclient/pull/752 was tested by TinFoilSubmarine but the ddclient maintainer seems to be MIA.   Is it possible to just change the hostname for use within OPNsense?

**Comment by AdSchellevis** [comment] 2024-11-27 07:48
@AhnHEL I don't expect we plan to fetch changes before a release anymore, past experiences haven't been great, which is also the reason why we wrote our own implementation at some point.

**Comment by Monviech** [comment] 2024-11-27 09:11
If the issue is pressing and won't be resolved before the API change deadline, I pulled the change into caddy last month.

https://github.com/opnsense/tools/pull/440

You can use that plugin as dyndns client as well.

**Comment by AhnHEL** [comment] 2024-12-19 23:16
The PR at https://github.com/ddclient/ddclient/pull/752 has finally been merged by a maintainer of ddclient.  Can we please get this updated?

**Comment by fichtner** [comment] 2024-12-23 14:04
https://github.com/ddclient/ddclient/commit/aba1df3e does not apply to 3.11.2 -- sorry we are not upstream and upstream should timely merge and release their stuff...

**Closed by fichtner** 2024-12-23 14:04 UTC

**Comment by fichtner** [comment] 2024-12-23 14:08
https://github.com/opnsense/ports/commit/9836aa7c7

**Comment by fichtner** [comment] 2024-12-23 16:15
We do have our native client nowadays which is also the default, perhaps at some point it makes sense to split off ddclient from the plugin. It depends on how upstream continues.

Editing the ddclient script file by hand is the best approach until 24.7.12 hits early next year.


Thanks and happy holidays!
Franco

**Comment by AhnHEL** [comment] 2024-12-28 19:48
@fichtner Just an FYI, finally some progress

https://github.com/ddclient/ddclient/releases/tag/v4.0.0-rc.1
