### ISSUE TITLE
refreshing problem public key webGUI wireguard 

### ISSUE THREAD

**Issue by boistordu** [opnsense/plugins#2375] opened 2021-05-04 16:01 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

the public key isn't printing after the connection have been made which is a bug.

**step to reproduce**
1/ Create a new wireguard link where only the private key for the local interface is giving to you in the conf file that your provider has sent to you.
2/ connect
3/ check again if in the local configuration tab, the public key is now showing as it does in the connection tab as shown in the third screenshot. 

**Screenshots**

![wireguardlocalconfig1](https://user-images.githubusercontent.com/9523075/117033471-aeda1600-ad02-11eb-9bc4-4273d08951e4.png)

in comparaison:
![wireguardconflocal0](https://user-images.githubusercontent.com/9523075/117033499-b6012400-ad02-11eb-9082-c60f5d18c3d3.png)

and this has been taken while it is connected :
![wireguard](https://user-images.githubusercontent.com/9523075/117033575-c7e2c700-ad02-11eb-88aa-17b4a4430099.png)

**Comment by fichtner** [comment] 2021-05-04 18:46
The plugin can't calculate the correct public key from the private key you were given while leaving the public key empty. It creates one for you if you save empty public and private key ... switching the private key afterwards will break it since you won't have the correct public key set up.

**Comment by fichtner** [comment] 2021-05-04 18:47
Actually I created a ticket for this so this may be a duplicate of #2308

**Comment by boistordu** [comment] 2021-05-05 23:25
Oooow okey, I thought it was retrieving it from the server while handshaking it. 
Okey now it's making more sense then. 
So it might be best that the config tab stays emptied then if it needs to calculate it at each changes.

Does it influence in anyway or could have consequences on the integrity of the tunnel or the packets inside and impeach the tunnel to be working properly ?

**Closed** 2021-10-31 15:05 UTC
