### ISSUE TITLE
os-acme-client - Automations broken

### ISSUE THREAD

**Issue by firefart** [opnsense/plugins#3807] opened 2024-02-07 14:34 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
The automation in the acme client plugin is not working. In this example the Fritz Box plugin is used.
I have the following error in `/tmp/PHP_errors.log`:
```text
[07-Feb-2024 15:24:23 Europe/Vienna] PHP Fatal error:  Uncaught TypeError: proc_open(): Argument #2 ($descriptor_spec) must be of type array, null given in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php:133
Stack trace:
#0 /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php(133): proc_open('/usr/local/sbin...', NULL, NULL, NULL, Array)
#1 /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php(106): OPNsense\AcmeClient\LeAutomation\Base->runAcme()
#2 /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php(606): OPNsense\AcmeClient\LeAutomation\Base->run()
#3 /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php(188): OPNsense\AcmeClient\LeCertificate->runAutomations()
#4 /usr/local/opnsense/scripts/OPNsense/AcmeClient/lecert.php(199): main()
#5 {main}
  thrown in /usr/local/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php on line 133
```

Debug Output:
```text
AcmeClient: running acme.sh command: /usr/local/sbin/acme.sh --deploy --syslog 7 --debug 3 --server 'https://xxxx/acme/acme/directory' --home '/var/etc/acme-client/home' --cert-home '/var/etc/acme-client/cert-home/x' --certpath '/var/etc/acme-client/certs/x/cert.pem' --keypath '/var/etc/acme-client/keys/x/private.key' --capath '/var/etc/acme-client/certs/x/chain.pem' --fullchainpath '/var/etc/acme-client/certs/x/fullchain.pem' --domain 'fritz.box' --deploy-hook fritzbox"
```

It looks like this commit https://github.com/opnsense/plugins/commit/f7837735ede0fd4c377a8c18cefe550ccc32bea9#diff-8ac6f7e50c9bcafab9d383912365821110a102238112717fe8408c48048bfeef removed the `$proc_desc` variable and it's now undefined.

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 24.1.1 (amd64).
os-acme-client 4.0

**Comment by fraenki** [comment] 2024-02-07 21:56
Duplicate of #3790.

**Closed by fraenki** 2024-02-07 21:56 UTC
