### ISSUE TITLE
misc/theme-cicada: IPsec view broken with Cicada

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#1997] opened 2020-08-24 13:56 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
With the new IPsec overview the Cicada theme has some style issues.
@opnsenseuser can you have a look at it?

**To Reproduce**
1. Switch to Cicada
2. Go to VPN : IPsec : Tunnel Settings

**Screenshots**
![image](https://user-images.githubusercontent.com/20438689/91052693-1becc600-e622-11ea-9e24-cc30822a648e.png)

**Additional context**
@marjohn56 I'm not sure if your current PR is related to this one

**Environment**
OPNsense 20.1.9

**Comment by opnsenseuser** [comment] 2020-08-24 14:00
Sure, but at the Moment im on vacation. Im back in 3 weeks. I will Fix this




Montag, 24. August 2020, 15:56 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by marjohn56** [comment] 2020-08-24 14:21
There was an issue with another list I corrected. Sadly I don;t use ipsec, but I'll take a look.

**Comment by marjohn56** [comment] 2020-08-24 14:25
Yes... well. :)
![image](https://user-images.githubusercontent.com/17962918/91056543-06759d00-e61e-11ea-88bf-8807a611e1ca.png)

**Comment by marjohn56** [comment] 2020-08-24 14:51
The problem is in the vpn_ipsec.php file. line 327 is using a fixed background colour. 🤔

**Comment by opnsenseuser** [comment] 2020-08-24 14:56
Can you Fix this? But be shure That everything else still works 



Gesendet von myMail für iOS


Montag, 24. August 2020, 16:51 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by marjohn56** [comment] 2020-08-24 14:58
Just add a couple of lines at the bottom of the css file to override it, in my case

.phase1_tr td {
  background-color: #333333 !important;
}

Seems to do the trick.

**Comment by marjohn56** [comment] 2020-08-24 15:08
rebellion theme fix is: #1999

**Comment by marjohn56** [comment] 2020-08-24 15:15
René - Do you want me to fix Cicada for you?

**Comment by opnsenseuser** [comment] 2020-08-24 15:27
If it doesnt bother you too much? Would ne nice

Regards René



Gesendet von myMail für iOS


Montag, 24. August 2020, 17:15 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by marjohn56** [comment] 2020-08-24 15:27
![image](https://user-images.githubusercontent.com/17962918/91064069-b0592780-e626-11ea-9704-7f796c1f23a5.png)

Is that too dark for yours?

**Comment by opnsenseuser** [comment] 2020-08-24 15:28
Great thx👍



Gesendet von myMail für iOS


Montag, 24. August 2020, 17:28 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by marjohn56** [comment] 2020-08-24 15:28
Cool. I'll issue the PR.

**Comment by opnsenseuser** [comment] 2020-08-24 15:29
👍



Gesendet von myMail für iOS


Montag, 24. August 2020, 17:29 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by marjohn56** [comment] 2020-08-24 15:36
fixed with #2000

**Comment by opnsenseuser** [comment] 2020-08-24 15:38
thx very much martin




Montag, 24. August 2020, 17:36 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by opnsenseuser** [comment] 2020-09-19 06:15
Hi Martin,

 

please close this pull request. I'm in the process of updating cicada and also the second theme vicuna and I will take over the changes from you right away. 

 

Thank you and have a nice day. 

 

Kind regards René

 

 

Von: Martin Wasley <notifications@github.com> 
Gesendet: Montag, 24. August 2020 17:36
An: opnsense/plugins <plugins@noreply.github.com>
Cc: René <rene@team-rebellion.net>; Mention <mention@noreply.github.com>
Betreff: Re: [opnsense/plugins] misc/theme-cicada: IPsec view broken with Cicada (#1997)

 

fixed with #2000 <https://github.com/opnsense/plugins/pull/2000>

**Comment by marjohn56** [comment] 2020-09-19 06:16
ok

**Comment by opnsenseuser** [comment] 2020-09-20 11:11
https://github.com/opnsense/plugins/pull/2037

**Closed** 2020-09-21 06:37 UTC
