### ISSUE TITLE
Add godaddy to Dynamic DNS plugin

### ISSUE THREAD

**Issue by APoniatowski** [opnsense/plugins#1589] opened 2019-11-23 02:14 UTC
[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
nope... don't have time to read it, or can I default to "yes", like all EULA's?

[-] I have searched the existing issues and I'm convinced that mine is new.
nope... last ticket was open for almost a year, no response.

[-] When the request is meant for an existing plugin, I've added its name to the title.
Dynamic DNS

**Is your feature request related to a problem? Please describe.**
Yes, there is no option to use godaddy with Dynamic DNS, without too much hassles

**Describe the solution you'd like**
add godaddy to dynamic DNS

**Describe alternatives you've considered**
The alternative would be... to add godaddy to dynamic DNS

**Additional context**
I believe I made it abundantly clear by now :)

**Comment by fichtner** [comment] 2019-11-23 06:31
> nope... don't have time to read it, or can I default to "yes", like all EULA's?

This really shouldn’t be a joke for you.

The issue is up for grabs. First contributor wins the credit.

I’m closing this since it’s a duplicate.


Cheers,
Franco

**Closed by fichtner** 2019-11-23 06:31 UTC

**Comment by fichtner** [comment] 2019-11-23 06:33
https://github.com/opnsense/plugins/issues/1108 placing link as further reference

**Comment by APoniatowski** [comment] 2019-11-23 12:55
It is technically a joke, as a feature addition is taking more than 8 months to implement (ticket was logged in March, last year, with someone else requesting the same thing in the ticket in Feb 2019).
"The issue is up for grabs. First contributor wins the credit.", so nobody will be working on it? as the ticket is not assigned to anyone, so is it safe to say, its better to migrate back to pfsense or even other firewall/routing products?

**Comment by fichtner** [comment] 2019-11-23 14:43
Well, it’s 8 months that you apparently did nothing as well by your logic. If you feel snarky again I’ll lock this topic.

**Comment by APoniatowski** [comment] 2019-11-23 15:56
"it’s 8 months that you apparently did nothing as well by your logic"... uhm... my firewall was fine, until the dashboard completely broke, with no logs to indicate what the issue was/is and also WAN was not getting an IP address. So I made the quick decision to migrate to opnsense (downloaded the ISO via my phone), as it is my home firewall. Discovered this issue, now I ended up with you, changing my perspective of this product and its community.

wow... stating a fact, is snarky? I think you need to look into what snarky means ("snide and sharply critical", and snide is mocking)... 
Seems like opnsense crowd is way more toxic than the pfsense crowd. While the opnsense crowd loves calling the pfsense crowd toxic.

lock the thread and do whatever you want to do, seems like "so-called-admins/devs" love abusing powers, by threatening and does not posses soft skills to read a situation, and resolve the matter. I won't be recommending opnsense to anyone, professionally, nor personally.

oh well... from disappointed/annoyed to irate, by one cocky dev. great job (now I'm being snarky, as you so eloquently put).

**Comment by fichtner** [comment] 2019-11-23 16:07
Just for the record  want to say two things:

1. Don't open a ticket against community best practice and try to win an argument about development resources that you don't offer either directly or indirectly.
2. OPNsense is not for you.

Locking as discussed.


Cheers,
Franco
