### ISSUE TITLE
dns/ddclient: add cloudns

### ISSUE THREAD

**Issue by nesth** [opnsense/plugins#2880] opened 2022-03-06 03:07 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Cloudns is support by ddclient, but not by OPNsense

**Describe the solution you'd like**
Either Cloudns provider support or a custom option with the ability to use a url 

**Describe alternatives you've considered**
Use the legacy as long as I can

**Additional context**

**Comment by STRUBartacus** [comment] 2022-03-18 08:04
https://github.com/ddclient/ddclient/pull/202

**Comment by djmixman** [comment] 2022-06-25 15:50
Has anyone come up with a work around to get ClouDNS working within OPNsense? I've gave up on trying to use ddclient until there is a fix, but it looks like the next upgrade will force me to switch and, well, its still not working as far as I can tell.

Right now, the only way I see getting this to work in the future is to just give up completely on ddclient and go back to using a cron script on one of the servers. :'(

**Comment by STRUBartacus** [comment] 2022-07-22 18:28
There's probably a small chance that ClouDNS support will be in 22.7, right?

**Comment by sja1440** [comment] 2022-08-25 13:10
I too use clouddns and so cannot migrate to os-ddclient until this issue is fixed.

**Closed** 2022-09-02 02:05 UTC

**Comment by kylernocturnalnerd** [comment] 2022-09-21 01:05
Is there no activity on this feature request? PFsense has cloudns in their option and their dyn allows for URL requests.
It's too bad.

**Comment by mtalexan** [comment] 2022-09-22 17:09
> Is there no activity on this feature request? PFsense has cloudns in their option and their dyn allows for URL requests. It's too bad.

If you check the official ddclient, there has only been two beta releases in the last years, and those are the ones that include ClouDNS support.

**Comment by webermax** [comment] 2022-10-12 19:17
It's too bad that it's still not possible to just enter a custom URL
 - just a simple client / browser based form validation issue (JS)?

**Comment by webermax** [comment] 2022-10-12 20:29
Thanks for the quick reply, gladly:

It's not possible to enter URL of the pattern "https://my-service.tld/endpoint/?par=val" as a valid server address getting the error message "please specify a valid address (IPv4/IPv6) or hostname" when trying to save a custom account.

**Comment by AdSchellevis** [comment] 2022-10-13 06:28
@webermax but have you confirmed that it does work when using the same input when changing ddclient's config file manually?

**Comment by kcris** [comment] 2023-05-26 17:47
I can confirm that 

opnsense gui does not work with cloudns

* the Cloudns entry type does not work
* the Custom entry type does not support full URL e.g. ipv4.cloudns.net/api/dynamicURL/?q=some-token-here

whereas manually editing the /usr/local/etc/ddclient.conf does work

```
use=cmd, cmd="/usr/local/opnsense/scripts/ddclient/checkip -t 1 -s ipify-ipv4 --timeout 10",
protocol=cloudns, \
dynurl=https://ipv4.cloudns.net/api/dynamicURL/?q=my-token-here, \
my-hostname.here
```


tested with opnsense 23.1.8
via Services/Dynamic DNS
backend=ddclient

Here is the official doc for cloudns.net showing the format of the custom url.
OpnSense gui does not allow it.
https://www.cloudns.net/wiki/article/36/

Thanks
