### ISSUE TITLE
haproxy multiselect menus messed up after 18.7 update

### ISSUE THREAD

**Issue by billyburly** [opnsense/plugins#769] opened 2018-08-01 03:06 UTC
After the update to 18.7 some of the multiselect menus in haproxy are messed up. Randomly displays the rules from one of the public frontends in the top right. Some of the multiselects have uuids instead of text.

![image](https://user-images.githubusercontent.com/741241/43498649-db3371fe-9515-11e8-9bb1-fafaa40811af.png)
![image](https://user-images.githubusercontent.com/741241/43498701-19c5e79e-9516-11e8-8449-2ec18752fa50.png)

**Comment by fichtner** [comment] 2018-08-01 05:12
Can you try to clear your browser cache?

**Comment by billyburly** [comment] 2018-08-01 05:39
persists with cleared cache. same issue in both firefox and chrome

**Comment by fichtner** [comment] 2018-08-01 06:07
You're right. This is caused by the haproxy.general.tuning.ssl_bindOptions field where there is an auto-complete which is shown in the upper left corner because it's pushed into an inconvenient place. I'll take a closer look.

**Comment by AdSchellevis** [comment] 2018-08-01 06:48
@fichtner not instantly, I've had some small glitches with the new tokeniser when working on the firewall aliases (I think it was this https://github.com/opnsense/core/blob/1a915fe80ca8c2c91cf4c1fcbc30ab630adcecca/src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt#L103), but I'm not sure 100% what the issue in this case is.  I will try to take a look later, using the HAProxy plugin,

**Comment by fichtner** [comment] 2018-08-01 07:02
looks similar. somehow the autocomplete window is shown, mostly due to bad style dropping it into the body...

https://github.com/opnsense/core/blob/1a915fe80ca8c2c91cf4c1fcbc30ab630adcecca/src/opnsense/www/js/tokenize2.js#L686-L687

**Comment by digitalcohesion** [comment] 2018-08-01 14:37
After applying the patch, it's improved in Safari, but I have to click in and out of the field to be able to type anything, and it also seems that Safari wants to offer to complete the field with contact addresses as well. This causes visual issues because of the placement of the menu widget. In the screenshot, what's actually typed into the field is 192.168, but the first two characters get cut off as the autofill menu is placed to the left instead of the right as usual.

![screen shot 2018-08-01 at 9 35 26 am](https://user-images.githubusercontent.com/4694328/43528310-492b337e-956e-11e8-9fbc-50e8a481f02c.png)

**Comment by digitalcohesion** [comment] 2018-08-01 19:43
Also I noticed that some of my settings don't show in the interface anymore. For example, the servers field on the Edit Backend page is blank, but I do have a server set for that backend, and it is in the haproxy.conf file when viewed in the shell.

![screen shot 2018-08-01 at 2 38 21 pm](https://user-images.githubusercontent.com/4694328/43544490-ac0f4c44-9598-11e8-9a1e-aea23bbc3c36.png)

**Comment by ikke-t** [comment] 2018-08-07 14:15
I also tried this. It did not fix it. The extra items menu disappeared from the corner, but now all the certs and rules are missing e.g. from the settings panel of Virtual Services -> Public Services -> Edit.

**Comment by digitalcohesion** [comment] 2018-08-07 15:09
Yes, I ended up reverting to the previous release which is working quite nicely.

**Comment by fichtner** [comment] 2018-08-07 15:31
Willing to fix but I don’t have a haproxy setup and are unable to reproduce. 😔

**Comment by AdSchellevis** [comment] 2018-08-07 15:54
likely this https://github.com/zellerda/Tokenize2/pull/38 issue, should be fixed with https://github.com/opnsense/core/commit/542331c93f0b9f6d639f719853c9ac5e8b28303c

to install:
```
opnsense-patch 542331
```

and then refresh your browser cache.

**Comment by astrandb** [comment] 2018-08-07 16:11
@fichtner @AdSchellevis 
The suggested patches do not help.
I can give you access to my test router where the problem is easy to see.

**Comment by AdSchellevis** [comment] 2018-08-07 16:29
@astrandb I seem to be able to reproduce the same here, but for some odd reason the patch works on the current development branch.

**Comment by AdSchellevis** [comment] 2018-08-07 17:09
Tried some different things, the problem seems to be the loading time of the modal in combination with the way Tokenizer2 seems to determine it's z-index. Slight variations cause the issue to vanish, but no concrete fix yet (on my end with safari and the patch installed, the issue doesn't exist).

The `zIndexMargin` parameter doesn't seem to resolve the issue either.

**Comment by AdSchellevis** [comment] 2018-08-08 16:47
@astrandb can you try https://github.com/opnsense/core/commit/31e3f748ad6a6ed2f0329f392ea705351d837d65 ?

```
opnsense-patch 31e3f7
```

**Comment by fichtner** [comment] 2018-08-08 17:30
From here this works better, I can now see the UUID display issue, but not sure what causes it.

**Comment by fichtner** [comment] 2018-08-08 17:45
We only push the value here: https://github.com/opnsense/core/blob/master/src/opnsense/www/js/opnsense_ui.js#L249

**Comment by astrandb** [comment] 2018-08-09 06:57
@AdSchellevis patch 31e3f7 takes care  of the misplaced multiselect menu. The UUID display issue is still there.

Same result with Edge and Chrome

**Comment by mimugmail** [comment] 2018-08-09 07:06
@AdSchellevis @fichtner Have you tried to remove `<style>tokenize</style>` from a multiselect field? I know this is just a workaround, but it helped my with the identical problem.

**Comment by fichtner** [comment] 2018-08-09 07:08
yes, but @fraenki insists on tokenize, which is a valid position ;) https://github.com/opnsense/plugins/pull/725

**Comment by AdSchellevis** [comment] 2018-08-09 07:08
@astrandb I missed that one, have to look into the token content, it seems to misplace our items here.

**Comment by mimugmail** [comment] 2018-08-09 07:10
Oh .. sort order, indeed :(

**Comment by AdSchellevis** [comment] 2018-08-09 18:55
@astrandb the uuid issue should be fixed with https://github.com/opnsense/core/commit/6e759fba30093d991071fb57e28130bde28b8eaf , can you try it out?

**Comment by astrandb** [comment] 2018-08-09 19:15
@AdSchellevis: Looking good on my test router.

**Comment by AdSchellevis** [comment] 2018-08-09 19:17
@astrandb thanks for confirming! I'll close the issue then

**Closed by AdSchellevis** 2018-08-09 19:17 UTC
Labels: bug

**Comment by fichtner** [comment] 2018-08-09 20:59
Added to 18.7.1 which hits early next week. Thanks all :)

**Comment by digitalcohesion** [comment] 2018-08-09 21:00
Nice. Thanks for fixing this one. I'll try the upgrade again with 18.7.1.

**Comment by ikke-t** [comment] 2018-08-10 06:51
I can also confirm it seems to work now. I applied patches: 31e3f7 and 6e759fb. The first one fixes the extra menu in the corner, and the second one hides the uuids and puts real names into place.

Thanks a lot for fixing it :)

**Comment by Addy90** [comment] 2018-08-10 09:45
Great, thank you for fixing - was just stumbling over this issue, and it is already fixed! Kudos for OPNsense! 👍

**Comment by ghostwheel42** [comment] 2018-08-14 21:45
@AdSchellevis your patches fix the messed up menu, but i think the sort order isn't retained anymore
(my haproxy warns about a http-request rule placed after a use-backend rule in a frontend)

**Comment by AdSchellevis** [comment] 2018-08-15 06:53
@ghostwheel42 can you open a new ticket for this (in core)?  I'm not sure this is related to the selectpicker itself, at a first glance the service seems to be returning the items sorted differently too.

**Comment by fichtner** [comment] 2018-08-15 06:57
probably related to https://github.com/opnsense/plugins/commit/701b3812f32c2b5ecc7c05ba42aaad205e3a85f2#diff-69d227db2482189cee05579ba25477f5 and https://github.com/opnsense/plugins/commit/c966d83c5954a

**Comment by AdSchellevis** [comment] 2018-08-15 07:01
@fichtner I don't expect this is the issue, the tokeniser is there, the service seems to supply the content alphabetically ordered (on my end).

**Comment by skynick11** [comment] 2018-08-15 17:27
The first screenshot shows that three fields are highlighted at the same time (and such "highlighted, but not selected" fields at "HAproxy" plugin page). The similar thing can be found at the "bind" plugin page. 

If click to the "highlighted" field, and after that click to some another field - the first field becomes "normal".

Is this a "known issue" or is it recommended to open a new ticket?

**Comment by ghostwheel42** [comment] 2018-08-15 19:44
@AdSchellevis you are probably right - the "Select Rules" under "Public Service" never were sorted.
S it's a bug/feature request for the HAProxy plugin.
Ordering matters, because the rules are nothing more than "if this then that" and it's easy to have a case rule that matches more than one rule. For example:
a) if path begins with /foo, then redirect to foo.domain.tld
b) if path begins with /foo/bar, then redirect to bar.domain.tld
When a) is before b), then b) will never match.

**Comment by AdSchellevis** [comment] 2018-08-15 19:49
maybe a weight on the rule could be an easy fix to achieve the desired behaviour, but that's just a possible solution for the issue. maybe it's better to open a new feature request and discuss with @fraenki
