### ISSUE TITLE
os-ddclient - Google invalid username

### ISSUE THREAD

**Issue by mikesimps** [opnsense/plugins#2780] opened 2022-01-29 11:23 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:
[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.
[x] The title contains the plugin to which this issue belongs

**Describe the bug**
When trying to setup a new configuration for Google Domains, the plugin is not allowing uppercase or numbers in the username and prevents you from saving the configuration. Since google generates credentials for you, this makes the plugin unusable for Google Domain Dynamic DNS. 

I used the legacy os-dyndns plugin prior to upgrading to 22.1 so it is not clear if this is a plugin issue or an OS issue.

**To Reproduce**
1. Go to Dynamic DNS: Settings
2. Click on "Add" to create a new entry (also fails on editing an existing one)
3. Enter in all required credential fields
4. Click Save
5. Get error "The username contains invalid characters."

**Expected behavior**
No errors when putting in valid Google domain credentials. Both upper case letters and numbers should be considered acceptable.

**Screenshots**
![Settings___Dynamic_DNS___Services___mike-opnsense_mas](https://user-images.githubusercontent.com/3085186/151658809-225586ea-346a-493c-a319-a919a65cce8e.png)

**Environment**
OPNsense 22.1
Unraid VM

**Comment by mimugmail** [comment] 2022-01-29 11:35
Duplicate of #2773

**Closed** 2022-01-29 11:37 UTC
