### ISSUE TITLE
ACME: Since 02/2018 no renewals are made

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/plugins#666] opened 2018-05-09 14:30 UTC
since 02/2018 there seems no attempt to have any renewals anylonger.

CloudFlare DNS01 method.

Extended Logs from acme.sh when using the `Issue/Renew Certificates Now` button:

```
[Wed May  9 16:21:24 CEST 2018] responseHeaders='HTTP/1.1 100 Continue
Expires: Wed, 09 May 2018 14:21:24 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 409 Conflict
Server: nginx
Content-Type: application/problem+json
Content-Length: 107
Boulder-Requester: 15399512
Location: https://acme-v01.api.letsencrypt.org/acme/reg/15399512
Replay-Nonce: <censored>
Expires: Wed, 09 May 2018 14:21:24 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 09 May 2018 14:21:24 GMT
Connection: close
'
[Wed May  9 16:21:24 CEST 2018] response='{"type":"urn:acme:error:malformed","detail":"Registration key is already in use","status": 409}'
[Wed May  9 16:21:24 CEST 2018] code='409'
[Wed May  9 16:21:24 CEST 2018] Already registered
[Wed May  9 16:21:24 CEST 2018] responseHeaders='HTTP/1.1 100 Continue
Expires: Wed, 09 May 2018 14:21:24 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 409 Conflict
Server: nginx
Content-Type: application/problem+json
Content-Length: 107
Boulder-Requester: 15399512
Location: https://acme-v01.api.letsencrypt.org/acme/reg/15399512
Replay-Nonce: <censored>
Expires: Wed, 09 May 2018 14:21:24 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 09 May 2018 14:21:24 GMT
Connection: close
'
[Wed May  9 16:21:24 CEST 2018] _accUri='https://acme-v01.api.letsencrypt.org/acme/reg/15399512'
[Wed May  9 16:21:24 CEST 2018] Calc CA_KEY_HASH='<censored>'
[Wed May  9 16:21:24 CEST 2018] ACCOUNT_THUMBPRINT='<censored>'
[Wed May  9 16:21:24 CEST 2018] _on_issue_err
[Wed May  9 16:21:24 CEST 2018] Please check log file for more details: /var/log/acme.sh.log
[Wed May  9 16:21:24 CEST 2018] _chk_vlist
```

I replaced some hashes with `<censored>` if anyone is wondering

Those are the logs when using `Forcefully (re-)issue the selected certificate?`

 level "debug":

```
[Wed May  9 16:31:30 CEST 2018] _on_before_issue
[Wed May  9 16:31:30 CEST 2018] _chk_main_domain='drupal-wiki.com'
[Wed May  9 16:31:30 CEST 2018] _chk_alt_domains='www.drupal-wiki.com'
[Wed May  9 16:31:30 CEST 2018] 'dns_cf' does not contain 'no'
[Wed May  9 16:31:30 CEST 2018] Le_LocalAddress
[Wed May  9 16:31:30 CEST 2018] d='drupal-wiki.com'
[Wed May  9 16:31:30 CEST 2018] Check for domain='drupal-wiki.com'
[Wed May  9 16:31:30 CEST 2018] _currentRoot='dns_cf'
[Wed May  9 16:31:30 CEST 2018] d='www.drupal-wiki.com'
[Wed May  9 16:31:30 CEST 2018] Check for domain='www.drupal-wiki.com'
[Wed May  9 16:31:30 CEST 2018] _currentRoot='dns_cf'
[Wed May  9 16:31:30 CEST 2018] d
[Wed May  9 16:31:30 CEST 2018] 'dns_cf' does not contain 'apache'
[Wed May  9 16:31:30 CEST 2018] _saved_account_key_hash='<censored>'
[Wed May  9 16:31:30 CEST 2018] _saved_account_key_hash is not changed, skip register account.
[Wed May  9 16:31:30 CEST 2018] Read key length:
[Wed May  9 16:31:30 CEST 2018] Creating domain key
[Wed May  9 16:31:30 CEST 2018] Using config home:/var/etc/acme-client/home
[Wed May  9 16:31:30 CEST 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Wed May  9 16:31:30 CEST 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Wed May  9 16:31:30 CEST 2018] _createkey for file:/var/etc/acme-client/home/drupal-wiki.com/drupal-wiki.com.key
[Wed May  9 16:31:30 CEST 2018] Use length 4096
[Wed May  9 16:31:30 CEST 2018] Using RSA: 4096
[Wed May  9 16:31:31 CEST 2018] The domain key is here: /var/etc/acme-client/home/drupal-wiki.com/drupal-wiki.com.key
[Wed May  9 16:31:31 CEST 2018] Create domain key error.
[Wed May  9 16:31:31 CEST 2018] pid
[Wed May  9 16:31:31 CEST 2018] No need to restore nginx, skip.
[Wed May  9 16:31:31 CEST 2018] _clearupdns
[Wed May  9 16:31:31 CEST 2018] skip dns.
[Wed May  9 16:31:31 CEST 2018] _on_issue_err
[Wed May  9 16:31:31 CEST 2018] Please check log file for more details: /var/log/acme.sh.log
[Wed May  9 16:31:31 CEST 2018] _chk_vlist
```

**Comment by EugenMayer** [comment] 2018-05-09 14:33
Not sure its the same reason, but i have this one too as an issue:

```
[Wed May  9 16:31:30 CEST 2018] _on_before_issue
[Wed May  9 16:31:30 CEST 2018] _chk_main_domain='drupal-wiki.com'
[Wed May  9 16:31:30 CEST 2018] _chk_alt_domains='www.drupal-wiki.com'
[Wed May  9 16:31:30 CEST 2018] 'dns_cf' does not contain 'no'
[Wed May  9 16:31:30 CEST 2018] Le_LocalAddress
[Wed May  9 16:31:30 CEST 2018] d='drupal-wiki.com'
[Wed May  9 16:31:30 CEST 2018] Check for domain='drupal-wiki.com'
[Wed May  9 16:31:30 CEST 2018] _currentRoot='dns_cf'
[Wed May  9 16:31:30 CEST 2018] d='www.drupal-wiki.com'
[Wed May  9 16:31:30 CEST 2018] Check for domain='www.drupal-wiki.com'
[Wed May  9 16:31:30 CEST 2018] _currentRoot='dns_cf'
[Wed May  9 16:31:30 CEST 2018] d
[Wed May  9 16:31:30 CEST 2018] 'dns_cf' does not contain 'apache'
[Wed May  9 16:31:30 CEST 2018] _saved_account_key_hash='Usxex62ZVbUUXDIx18V9wFb+MTP8qPMx4/fLMExy1Sg='
[Wed May  9 16:31:30 CEST 2018] _saved_account_key_hash is not changed, skip register account.
[Wed May  9 16:31:30 CEST 2018] Read key length:
[Wed May  9 16:31:30 CEST 2018] Creating domain key
[Wed May  9 16:31:30 CEST 2018] Using config home:/var/etc/acme-client/home
[Wed May  9 16:31:30 CEST 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Wed May  9 16:31:30 CEST 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Wed May  9 16:31:30 CEST 2018] _createkey for file:/var/etc/acme-client/home/drupal-wiki.com/drupal-wiki.com.key
[Wed May  9 16:31:30 CEST 2018] Use length 4096
[Wed May  9 16:31:30 CEST 2018] Using RSA: 4096
[Wed May  9 16:31:31 CEST 2018] The domain key is here: /var/etc/acme-client/home/drupal-wiki.com/drupal-wiki.com.key
[Wed May  9 16:31:31 CEST 2018] Create domain key error.
[Wed May  9 16:31:31 CEST 2018] pid
[Wed May  9 16:31:31 CEST 2018] No need to restore nginx, skip.
[Wed May  9 16:31:31 CEST 2018] _clearupdns
[Wed May  9 16:31:31 CEST 2018] skip dns.
[Wed May  9 16:31:31 CEST 2018] _on_issue_err
[Wed May  9 16:31:31 CEST 2018] Please check log file for more details: /var/log/acme.sh.log
[Wed May  9 16:31:31 CEST 2018] _chk_vlist
```

**Comment by EugenMayer** [comment] 2018-05-13 07:31
Feel free to close this issue anytime if its not a generic issue - i am not longer using the LE plugin so put not time to solve it for me specificly

**Comment by DonMcCoy** [comment] 2018-05-18 23:26
@EugenMayer I'm having frequently the same issue too, the first renewal attempt fails sometimes and the second works, I will examine and solve it over the weekend.

**Comment by EugenMayer** [comment] 2018-05-19 06:48
we had the same unreliable process, every second or third manual retrigger. the in entirely broke. we have a rancher base LE DNS01 and a cerbot/acme. sh base one, rather a couple, for about 60 certs. they all worked during the whole time without such things once - so it's definitely a local OPN related issue.

we switched for OPN haproxy + traefik and things are working very smooth now. maybe it's just us.

**Comment by fraenki** [comment] 2018-05-23 14:57
@DonMcCoy Were you able to further track this down? I'd gladly work on a fix if you find a way to reliably reproduce it.

**Comment by DonMcCoy** [comment] 2018-05-24 21:10
Hi @fraenki, I'm doing now auto renewal everyday and collect the logs, I got some warnings from certhelper.php that can help us to trace it down, I will update you soon.

**Comment by fraenki** [comment] 2018-05-24 23:38
@DonMcCoy A long standing bug was recently fixed (not yet released), maybe apply the patch manually from #682 to avoid hitting this old bug during your tests.

**Comment by DonMcCoy** [comment] 2018-05-27 21:43
Okay @fraenki after investigating a bit further, I noticed also your mentioned bug "node no longer exists error", after applying I never failed to issue manually till now, I setted the renewal to everyday, we will test for one week, if we didn't hit a fail, then this bug can be closed.

**Comment by EugenMayer** [comment] 2018-06-01 09:27
i upgraded to 18.1.9 and have the same issues - verifcation fails. Other implementation of ACME.sh / certbot and LEGO ( le golang ) are working fine on the same network and same domains.

```
[Fri Jun  1 11:25:06 CEST 2018] Create domain key error.
[Fri Jun  1 11:25:06 CEST 2018] pid
[Fri Jun  1 11:25:06 CEST 2018] No need to restore nginx, skip.
[Fri Jun  1 11:25:06 CEST 2018] _clearupdns
[Fri Jun  1 11:25:06 CEST 2018] skip dns.
[Fri Jun  1 11:25:06 CEST 2018] _on_issue_err
[Fri Jun  1 11:25:06 CEST 2018] Please check log file for more details: /var/log/acme.sh.log
```

`Create domain key error.` whatever this means - this time

**Comment by EugenMayer** [comment] 2018-06-01 09:29
could be related https://forum.opnsense.org/index.php?topic=7632.0

**Comment by ghostwheel42** [comment] 2018-08-14 08:13
I think I managed to get rid of the "Create domain key error" by adding a "return 0" to acme.sh in the createDomainKey function.
https://github.com/Neilpang/acme.sh/pull/1788/commits/7aeb113c62dee96e259229028ed349828d982dac

**Comment by DonMcCoy** [comment] 2018-08-14 09:55
That's wonderful @ghostwheel42 thanks a lot, and yes It solves the problem, testing before "return 0":
1. Create new domain (it shouldn't be added already)
2. hit issue cert
3. in the logs the first issue trial will fail with create domain key error and the second will succeed.

But after the return 0 it works.

This issue can be closed once the mentioned PR from acme.sh repo got accepted and we updated our acme.sh here to have the modified version.

Thanks

**Comment by fichtner** [comment] 2018-09-23 18:13
@ghostwheel42 thanks! closing since the commit was merged to acme.sh end of August.

**Closed by fichtner** 2018-09-23 18:13 UTC
Labels: upstream
