### ISSUE TITLE
net/haproxy: restart timeout

### ISSUE THREAD

**Issue by Taomyn** [opnsense/plugins#1463] opened 2019-08-21 18:34 UTC
WIth OPNsense 19.7.2 and HAProxy 2.17, if I use the restart option under Diagnostics, Services, the bar appears for a very long time, several minutes and disappears with the service running.

The GUI logs show the restart request is made, but on later says it timed out.

**Comment by fraenki** [comment] 2019-08-26 10:22
@Taomyn Could you please test on the console? This would help to see if it's a breakage in the GUI or an application error.

```configctl haproxy restart```

**Comment by Taomyn** [comment] 2019-08-26 11:15
@fraenki when I run the command I get:

`error in configd communication %s, see syslog for details`

I do not have seamless reloads enabled, the only option in that section enabled is the main "Enable HAProxy".

**Comment by fraenki** [comment] 2019-08-26 11:20
> see syslog for details

Could you also check `System: Log Files: Backend` and `System: Log Files: General` for additional information when running the `configctl` command? Thanks!

**Comment by Taomyn** [comment] 2019-08-26 11:27
@fraenki in General:

`Aug 26 13:26:13 	/configd_ctl.py: error in configd communication Traceback (most recent call last): File "/usr/local/opnsense/service/configd_ctl.py", line 65, in exec_config_cmd line = sock.recv(65536).decode() socket.timeout: timed out`

In Backend:

```
Aug 26 13:25:41 	configd.py: [87f1a552-9c8a-437c-bb1c-aad9f4e991df] Show system activity
Aug 26 13:24:13 	configd.py: [a176d002-afb3-491e-bd35-e3595d14e8b9] restarting haproxy
```

**Comment by Taomyn** [comment] 2019-08-28 13:43
FYI, still happens in 19.7.3 - so my Let's Encrypt certificates are royally screwed as HAProxy isn't getting restarted either.

**Comment by fraenki** [comment] 2019-09-03 13:51
@Taomyn Unfortunately, I still cannot reproduce it. Could you add your haproxy.conf (with sensitive information obfuscated)?

**Comment by Taomyn** [comment] 2019-09-04 07:27
@fraenki I uploaded it here https://pastebin.com/vesfhF6L hopefully I haven't overdone the redaction

**Comment by fraenki** [comment] 2019-10-10 10:54
@Taomyn Sorry that it took me so long to reply. I've checked your configuration and noticed the following backend configuration:

```
# Backend: DesktopCentral (Desktop Central)
backend DesktopCentral
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m
    stick on src
    # tuning options
    timeout connect 30000
    timeout server 30m
```

Wild guess: the `30m` timeout value might be the reason why restarts don't work for you.

One more suggestion: please ensure that `Graceful stop` is _not_ enabled in HAProxy's `Service Settings`. The following settings are the most reliable for frequent restarts that I can think of:

![Screenshot at 2019-10-10 12-53-14](https://user-images.githubusercontent.com/909706/66562938-fddabc00-eb5c-11e9-8651-f425e834e7ba.png)

**Comment by fraenki** [comment] 2019-10-10 10:55
Today's OPNsense update will include an upgrade from HAProxy 1.8 to 2.0, it might be worth to test this too.

**Comment by Taomyn** [comment] 2019-10-10 11:11
@fraenki no worries. That timeout is the same for all virtual services and isn't something I ever recall setting myself. When I create a new one it's the same value, so I didn't copy it from another entry. I also checked, and "Graceful stop" is not enabled.

I will of course try v2.0 when it drops and report back here.

**Comment by fraenki** [comment] 2019-11-04 21:58
I'll close this ticket now, but please report back if it is not fixed – and I'll reopen it.

**Closed by fraenki** 2019-11-04 21:58 UTC
Labels: support
