### ISSUE TITLE
CA not available to HAProxy since 18.7.8

### ISSUE THREAD

**Issue by Alex9779** [opnsense/plugins#1073] opened 2018-12-17 15:22 UTC
So after the update to 18.7.8 and still in 18.7.9 my HAProxy config stopped working.
Checking the config I got:
```
[/usr/local/etc/haproxy.conf:356] unable to load CA file '/tmp/haproxy/ssl/5b3f2ffa8b27d.pem'.
[ALERT] 350/162000 (34309) : Fatal errors found in configuration.
```
I found that this is a server entry configure to verify the SSL certificate with a CA I created.
In the server edit dialog I checked "Verify SSL certificate" and selected my CA from the dropdown.
But it seems the CA is not copied to that temp path the config refers to.
Still seems to work with all other certs from the ACME client as those are still there and updated when the HAProxy deamon reloads...
As a workaround I disabled the verification but still it seems to be a bug...

**Comment by zaggash** [comment] 2018-12-18 10:16
Duplicate, as far as I can see it is the same issue.

**Comment by fraenki** [comment] 2018-12-18 15:13
duplicate of #1074

**Closed by fraenki** 2018-12-18 15:13 UTC
Labels: bug

**Comment by Alex9779** [comment] 2018-12-19 07:01
Hey but mine has a lower number, I was first :D ^^ That's why I didn't find it when I search open bugs for similar reports...
All good :)
